
# Run localisation

trigger: none

pr: none

pool:
  vmImage: 'vs2017-win2016'

steps:
   - task: OneLocBuild@2
     inputs:
       locProj: 'Localize/LocProject.json'
       outDir: '$(Build.ArtifactStagingDirectory)'
       repoType: gitHub
       isEnablePseudoLanguagesSelected: true
       isCreatePrSelected: true
       gitHubPatVariable: $(GithubPAT)
       gitHubPrMergeMethod: squash
       packageSourceAuth: 'patAuth'
       patVariable: $(OneLocBuildPAT)

       steps:
- task: cesve.one-loc-build.one-loc-build.OneLocBuild@2
  displayName: 'Localization Build: Localize/LocProject.json'
  inputs:
    isEnablePseudoLanguagesSelected: false
    isCreatePrSelected: true
    repoType: gitHub
    gitHubPatVariable: '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 '
    gitHubPrMergeMethod: squash
    packageSourceAuth: patAuth
    patVariable: 7w3jp6u64yzr3mwgrzpzehk3zqum2coc6n3u54ekfpugiuxcnegq



   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: loc'
     inputs:
       ArtifactName: loc