
# Run localisation

trigger: none

pr: none

pool:
  vmImage: "windows-latest"

steps:
   - task: OneLocBuild@2
     inputs:
       locProj: 'Localize/LocProject.json'
       outDir: '$(Build.ArtifactStagingDirectory)'
       packageSourceAuth: 'patAuth'
       patVariable: $(OneLocBuildPAT)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: loc'
      inputs:
        ArtifactName: loc