import { describe, vi, beforeEach, afterEach, beforeAll, afterAll, it, test, expect } from 'vitest';
import { createYamlFromMap } from '../MapDefinitionSerializer';
import { MapDefinitionEntry } from '@microsoft/logic-apps-shared';

describe('serialization helpers', () => {
  describe('createYamlFromMap', () => {
    it('try array', () => {
      const mapDefinition = {
        $version: '1.0',
        $input: 'XML',
        $output: 'XML',
        $sourceSchema: 'Source.xsd',
        $targetSchema: 'Target.xsd',
        $sourceNamespaces: {
          ns0: 'http://tempuri.org/source.xsd',
          xs: 'http://www.w3.org/2001/XMLSchema',
        },
        $targetNamespaces: {
          ns0: 'http://tempuri.org/Target.xsd',
          td: 'http://tempuri.org/TypeDefinition.xsd',
          xs: 'http://www.w3.org/2001/XMLSchema',
        },
        'ns0:Root': {
          DirectTranslation: {
            Employee: [{ ID: '/ns0:Root/DirectTranslation/EmployeeID' }, { Name: '/ns0:Root/DirectTranslation/EmployeeName' }],
          },
        },
      };
      const map = createYamlFromMap(mapDefinition as any as MapDefinitionEntry, targetSchemaSortArray);
      console.log(map);
    });
  });
});

const targetSchemaSortArray = [
  '/ns0:Root',
  '/ns0:Root/DirectTranslation',
  '/ns0:Root/DirectTranslation/Employee',
  '/ns0:Root/DirectTranslation/Employee/ID',
  '/ns0:Root/DirectTranslation/Employee/Name',
  '/ns0:Root/DataTranslation',
  '/ns0:Root/DataTranslation/EmployeeName',
  '/ns0:Root/DataTranslation/EmployeeName/@RegularFulltime',
  '/ns0:Root/DataTranslation/EmployeeName/@<AnyAttribute>',
  '/ns0:Root/ContentEnrich',
  '/ns0:Root/ContentEnrich/DateOfDemo',
  '/ns0:Root/CumulativeExpression',
  '/ns0:Root/CumulativeExpression/PopulationSummary',
  '/ns0:Root/CumulativeExpression/PopulationSummary/State',
  '/ns0:Root/CumulativeExpression/PopulationSummary/State/Name',
  '/ns0:Root/CumulativeExpression/PopulationSummary/State/SexRatio',
  '/ns0:Root/ConditionalMapping',
  '/ns0:Root/ConditionalMapping/ItemPrice',
  '/ns0:Root/ConditionalMapping/ItemQuantity',
  '/ns0:Root/ConditionalMapping/ItemDiscount',
  '/ns0:Root/Looping',
  '/ns0:Root/Looping/Person',
  '/ns0:Root/Looping/Person/Name',
  '/ns0:Root/Looping/Person/Address',
  '/ns0:Root/Looping/Person/Other',
  '/ns0:Root/Looping/Person/Publisher',
  '/ns0:Root/Looping/Trips',
  '/ns0:Root/Looping/Trips/Trip',
  '/ns0:Root/Looping/Trips/Trip/VehicleRegistration',
  '/ns0:Root/Looping/Trips/Trip/Distance',
  '/ns0:Root/Looping/Trips/Trip/Duration',
  '/ns0:Root/ConditionalLooping',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/PetProduct',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/PetProduct/Name',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/PetProduct/SKU',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/PetProduct/Price',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/GroovyProduct',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/GroovyProduct/Name',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/GroovyProduct/SKU',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/GroovyProduct/Price',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/OfficeProduct',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/OfficeProduct/Name',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/OfficeProduct/SKU',
  '/ns0:Root/ConditionalLooping/CategorizedCatalog/OfficeProduct/Price',
  '/ns0:Root/LoopingWithIndex',
  '/ns0:Root/LoopingWithIndex/WeatherSummary',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1/Name',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1/Pressure',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1/WindSpeed',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1/Temperature',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day1/<AnyElement>',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2/Name',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2/Pressure',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2/WindSpeed',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2/Temperature',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day2/<AnyElement>',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day/Name',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day/Pressure',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day/WindSpeed',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day/Temperature',
  '/ns0:Root/LoopingWithIndex/WeatherSummary/Day/<AnyElement>',
  '/ns0:Root/NameValueTransforms',
  '/ns0:Root/NameValueTransforms/FlatterCatalog',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price/Pen',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price/Pencil',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price/NoteBook',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price/Bag',
  '/ns0:Root/NameValueTransforms/FlatterCatalog/Price/Others',
  '/ns0:Root/NameValueTransforms/PO_Status',
  '/ns0:Root/NameValueTransforms/PO_Status/ShipDate',
  '/ns0:Root/NameValueTransforms/PO_Status/ShippedVia',
  '/ns0:Root/NameValueTransforms/PO_Status/Product',
  '/ns0:Root/NameValueTransforms/PO_Status/Product/ProductIdentifier',
  '/ns0:Root/NameValueTransforms/PO_Status/Product/OrderStatusQuantity',
  '/ns0:Root/NameValueTransforms/PO_Status/Product/OrderStatusQuantity/GlobalOrderQuantityTypeCode',
  '/ns0:Root/NameValueTransforms/PO_Status/Product/OrderStatusQuantity/ProductQuantity',
];
