import { defineConfig } from 'tsup';
import { lessLoader } from 'esbuild-plugin-less';

export default defineConfig({
  entry: ['src/index.ts'],
  treeshake: true,
  outDir: 'build/lib',
  sourcemap: true,
  minify: true,
  clean: true,
  // dts: true,
  splitting: false,
  tsconfig: 'tsconfig.json',
  format: ['esm'],
  external: [
    'react',
    'react-dom',
    '@microsoft/logic-apps-shared',
    '@microsoft/designer-ui',
    '@microsoft/logic-apps-designer',
    '@fluentui/azure-themes',
    '@fluentui/react',
    '@fluentui/react-components',
    '@fluentui/react-hooks',
    '@fluentui/react-icons',
    '@fluentui/react-migration-v8-v9',
    '@fluentui/react-portal-compat',
    '@microsoft/applicationinsights-react-js',
    '@microsoft/applicationinsights-web',
    '@react-hookz/web',
    '@reduxjs/toolkit',
    'fuse.js',
    'immer',
    'js-yaml',
    'pathfinding',
    'react-dnd',
    'react-dnd-html5-backend',
    'react-icons',
    'react-intl',
    'react-redux',
    'reactflow',
    'redux-thunk',
    'redux-undo',
    'yaml',
    'yaml-types',
    '@tanstack/react-query',
    '@tanstack/react-query-devtools',
  ],
  injectStyle: false,
  loader: {
    '.svg': 'dataurl',
  },
  esbuildPlugins: [lessLoader()],
});
