<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:samples:import-missing"
           xmlns="urn:samples:import-missing"
           elementFormDefault="qualified">
  <xs:import namespace="urn:samples:missing" schemaLocation=".\NotThere.xsd"/>
  <xs:element name="Order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderId" type="xs:string"/>
        <xs:element name="CustomerName" type="xs:string"/>
        <xs:element name="ShipTo">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Street" type="xs:string"/>
              <xs:element name="City" type="xs:string"/>
              <xs:element name="PostalCode" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Total" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
