<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:c="urn:samples:common"
           xmlns:w="urn:samples:wrapper"
           targetNamespace="urn:samples:import-diamond"
           xmlns="urn:samples:import-diamond"
           elementFormDefault="qualified">
  <xs:import namespace="urn:samples:common" schemaLocation=".\Common.xsd"/>
  <xs:import namespace="urn:samples:wrapper" schemaLocation=".\Shared\Wrapper.xsd"/>
  <xs:element name="Order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderId" type="xs:string"/>
        <xs:element name="CustomerName" type="xs:string"/>
        <xs:element name="ShipTo" type="c:AddressType"/>
        <xs:element name="Total" type="xs:decimal"/>
        <xs:element name="Related" type="w:OrderBodyType" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
