<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:c="urn:samples:common"
           targetNamespace="urn:samples:target-import"
           xmlns="urn:samples:target-import"
           elementFormDefault="qualified">
  <xs:import namespace="urn:samples:common" schemaLocation=".\Common.xsd"/>
  <xs:element name="Invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="InvoiceId" type="xs:string"/>
        <xs:element name="Customer" type="xs:string"/>
        <xs:element name="BillTo" type="c:AddressType"/>
        <xs:element name="Amount" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
