steps:
  - task: NodeTool@0
    displayName: "👉 Using Node.js"
    inputs:
      versionSource: fromFile
      versionFilePath: .nvmrc
    condition: succeeded()

  - script: npm install -g pnpm
    displayName: "👉 Install pnpm"
    condition: succeeded()

  - script: pnpm install --no-optional
    displayName: "👉 Install Dependencies with pnpm"
    workingDirectory: $(working_directory)
    condition: succeeded()
    
  - task: Npm@1
    displayName: "Build"
    inputs:
      command: custom
      customCommand: run build:extension
      workingDir: $(working_directory)
    condition: succeeded()
    