steps:
  - script: npx tsx scripts/get-current-version.ts "$(Build.SourceBranchName)"
    displayName: "Get Current Version"
    workingDirectory: $(working_directory)
    condition: succeeded()
    name: version

  - script: node scripts/update-versions.js $(version.current_version)
    displayName: "Update Version in Package Files"
    workingDirectory: $(working_directory)
    condition: succeeded()

  - pwsh: |
      (Get-Content apps/vs-code-designer/src/package.json -Raw) -replace '"aiKey":\s*"[^"]*"', '"aiKey": "3cf0d6ae-3327-414a-b7c1-12f31ef45eff"' | Set-Content apps/vs-code-designer/src/package.json -NoNewline
    displayName: "Set Designer Extension VSIX aiKey in package.json"
    workingDirectory: $(working_directory)
    condition: succeeded()

  - script: npx replace-in-file setInGitHubBuild $(AI_KEY) apps/vs-code-designer/src/main.ts
    displayName: "Replace Placeholder with Telemetry Key"
    workingDirectory: $(working_directory)
    condition: succeeded()

  - script: pnpm run vscode:designer:pack
    displayName: "Package with pnpm"
    workingDirectory: $(working_directory)
    condition: succeeded()
    