steps:
  - task: Npm@1
    displayName: "Package"
    inputs:
      command: custom
      customCommand: run vscode:designer:pack
      workingDir: $(working_directory)
    condition: succeeded()
    