steps:
  - pwsh: |
      $version = $(npx tsx scripts/get-current-version.ts "$(Build.SourceBranchName)")
      Write-Host "Current version: $version"
      Write-Host "##vso[task.setvariable variable=current_version;isOutput=true]$version"
    displayName: "Get Current Version"
    workingDirectory: $(working_directory)
    condition: succeeded()
    name: version
    id: get_version

  - script: node scripts/update-versions.js $(current_version)
    displayName: "Update Version in Package Files"
    workingDirectory: $(working_directory)
    condition: succeeded()
    env:
      current_version: $(get_version.current_version)

  - pwsh: |
      (Get-Content apps/vs-code-designer/src/package.json -Raw) -replace '"aiKey":\s*"[^"]*"', '"aiKey": "$(AI_KEY)"' | Set-Content apps/vs-code-designer/src/package.json -NoNewline
    displayName: "Set Designer Extension VSIX aiKey in package.json"
    workingDirectory: $(working_directory)
    condition: succeeded()

  - script: npx replace-in-file setInGitHubBuild $(AI_KEY) apps/vs-code-designer/src/main.ts
    displayName: "Replace Placeholder with Telemetry Key"
    workingDirectory: $(working_directory)
    condition: succeeded()

  - script: pnpm run vscode:designer:pack
    displayName: "Package with pnpm"
    workingDirectory: $(working_directory)
    condition: succeeded()
    