name: '🐞 Logic Apps/Power Automate Bug Report'
description: Create a report to help us improve Logic Apps
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for reporting bugs found in Logic Apps UI (https://github.com/Azure/LogicAppsUX)
        If you have a question about how to achieve something and are struggling with a broader Logic App issue, please post a question
        inside of Logic App's Discussion repo: https://github.com/Azure/LogicApps/discussions
        If it's an issue about the docs, please go to the Logic App's documentation repo (https://github.com/Azure/logicapps)

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - Open Issue's tab: https://github.com/Azure/LogicAppsUX/issues?q=is%3Aissue+sort%3Aupdated-desc+position
         - Closed Issues tab: https://github.com/Azure/LogicAppsUX/issues?q=is%3Aissue+sort%3Aupdated-desc+position+is%3Aclosed

        Please refer to the Troubleshooting Guide to help with filling in this information: https://aka.ms/lauxtsg
        The more information you fill in, the better we can help you.

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug with repro steps
      description: Provide a clear and concise description of the challenge you are running into.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true

  - type: dropdown
    id: sku
    attributes:
      label: What type of Logic App Is this happening in?
      options:
        - Consumption (Portal)
        - Power Automate
        - Standard (Portal)
        - Standard (VSCode)
    validations:
      required: true

  - type: dropdown
    id: designerType
    attributes:
      label: Are you using new designer or old designer
      options:
        - New Designer
        - Old Designer
    validations:
      required: true

  - type: dropdown
    id: tsgchecked
    attributes:
      label: Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow JSON
      description: If able, provide a workflow json that reproduces the issue.
      placeholder: |
        {
            "definition": {
            "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
            "actions": {},
            "contentVersion": "1.0.0.0",
            "outputs": {},
            "triggers": {}
          },
          "kind": "Stateful"
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓

  - type: textarea
    id: browser
    attributes:
      label: Browser
      placeholder: |
        - Browser: [e.g. Chrome, Safari, Firefox]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
