import { defineConfig } from 'tsup';
import { lessLoader } from 'esbuild-plugin-less';

export default defineConfig({
  entry: ['src/index.ts'],
  treeshake: true,
  outDir: 'build/lib',
  sourcemap: true,
  minify: true,
  clean: true,
  // dts: true,
  splitting: false,
  tsconfig: 'tsconfig.json',
  format: ['esm'],
  external: [
    'react',
    'react-dom',
    '@microsoft/logic-apps-shared',
    '@microsoft/designer-ui',
    '@microsoft/logic-apps-chatbot',
    '@fluentui/azure-themes',
    '@fluentui/react',
    '@fluentui/react-components',
    '@fluentui/react-hooks',
    '@fluentui/react-icons',
    '@fluentui/utilities',
    '@microsoft/applicationinsights-core-js',
    '@react-hookz/web',
    '@reduxjs/toolkit',
    '@xyflow/react',
    '@xyflow/react/dist/style.css',
    'elkjs',
    'file-saver',
    'fuse.js',
    'immer',
    'jszip',
    'lodash.frompairs',
    'lodash.isequal',
    'lodash.merge',
    'lz-string',
    'pako',
    'react-dnd',
    'react-dnd-accessible-backend',
    'react-dnd-html5-backend',
    'react-dnd-multi-backend',
    'react-hotkeys-hook',
    'react-intl',
    'react-markdown',
    'react-redux',
    'react-window',
    'redux-thunk',
    'reselect',
    'tabster',
    'to-title-case',
    '@tanstack/react-query',
    '@tanstack/react-query-devtools',
    '@tanstack/react-query-persist-client',
    '@tanstack/query-sync-storage-persister',
  ],
  injectStyle: false,
  loader: {
    '.svg': 'dataurl',
  },
  esbuildPlugins: [lessLoader()],
});
