import type { WorkflowEdge, WorkflowNode } from '../../parsers/models/workflowNode';
import type { RootState } from '../../store';
import type { NodesMetadata, WorkflowState } from './workflowInterfaces';
import type { LogicAppsV2 } from '@microsoft/logic-apps-shared';
import type { OperationMetadataState } from '../operation/operationMetadataSlice';
export declare const getWorkflowState: (state: RootState) => WorkflowState;
export declare const getWorkflowAndOperationState: (state: RootState) => {
    workflow: WorkflowState;
    operations: OperationMetadataState;
};
export declare const useNodeDisplayName: (id?: string) => string;
export declare const useNodeReplacedId: (id?: string) => string | undefined;
export declare const useReplacedIds: () => Record<string, string>;
export declare const useNodeMetadata: (id?: string) => import("./workflowInterfaces").NodeMetadata | undefined;
export declare const useActionMetadata: (id?: string) => LogicAppsV2.OperationDefinition | undefined;
export declare const useNodeDescription: (id: string) => string | undefined;
export declare const useShouldNodeFocus: (id: string) => boolean;
export declare const useFocusElement: () => string | undefined;
export declare const useIsWorkflowDirty: () => boolean;
export declare const useWorkflowChangeCount: () => number;
export declare const useTimelineRepetitionIndex: () => number;
export declare const useTimelineRepetitionArray: () => string[][];
export declare const useActionTimelineRepetitionCount: (actionId: string, index: number) => number;
export declare const useIsActionInSelectedTimelineRepetition: (actionId: string) => boolean;
export declare const useIsEverythingExpanded: () => boolean;
export declare const useWorkflowGraph: () => WorkflowNode | null;
export declare const useRootWorkflowGraphForLayout: () => WorkflowNode | undefined;
export declare const useCollapsedMapping: () => Record<string, string[]>;
export declare const useIsGraphCollapsed: (graphId: string) => boolean;
export declare const useIsActionCollapsed: (actionId: string) => boolean;
export declare const useGetSwitchOrAgentParentId: (nodeId: string) => {
    parentId?: string;
    type?: string;
} | undefined;
export declare const useEdgesBySource: (parentId?: string) => WorkflowEdge[];
export declare const getWorkflowNodeFromGraphState: (state: WorkflowState, actionId: string) => WorkflowNode | undefined;
export declare const useNodeEdgeTargets: (nodeId?: string) => string[];
export declare const useWorkflowNode: (actionId?: string) => WorkflowNode | undefined;
export declare const useIsGraphEmpty: () => boolean;
export declare const useIsLeafNode: (nodeId: string) => boolean;
export declare const useFlowErrors: () => Record<string, string[]>;
export declare const useFlowErrorsForNode: (nodeId: string) => string[];
export declare const useNodeIds: () => string[];
export declare const useNewAdditiveSubgraphId: (baseId: string) => string;
export declare const useConnectedRootGraphNodeIds: () => string[];
export declare const useDisconnectedNodes: () => string[];
export declare const useIsDisconnected: (nodeId: string) => boolean;
export declare const useAllGraphParents: (graphId: string) => string[];
export declare const getParentsUncollapseFromGraphState: (state: WorkflowState, actionId: string) => Record<string, boolean>;
export declare const useNodeGraphId: (nodeId: string) => string;
export declare const useGetAllOperationNodesWithin: (nodeId: string) => string[];
export declare const getWorkflowGraphPath: (graph: WorkflowNode, graphId: string) => string[];
export declare const useRunInstance: () => LogicAppsV2.RunInstanceDefinition | null;
export declare const useRunMode: () => string | null;
export declare const useRetryHistory: (id: string) => LogicAppsV2.RetryHistory[] | undefined;
export declare const useRunData: (id: string) => LogicAppsV2.WorkflowRunAction | LogicAppsV2.WorkflowRunTrigger | undefined;
export declare const useToolRunData: (id: string) => LogicAppsV2.WorkflowRunAction | LogicAppsV2.WorkflowRunTrigger | undefined;
export declare const useSubgraphRunData: (id: string) => Record<string, {
    actionResults: LogicAppsV2.WorkflowRunAction[];
}> | undefined;
export declare const useNodesMetadata: () => NodesMetadata;
export declare const getNodesWithGraphId: (graphId: string, nodesMetadata: NodesMetadata) => NodesMetadata;
export declare const useParentRunIndexes: (id: string | undefined) => Record<string, number>;
export declare const useParentRunIndex: (id: string | undefined) => number | undefined;
export declare const useRunIndex: (id: string | undefined) => number | undefined;
export declare const useToolRunIndex: (id: string | undefined) => number | undefined;
export declare const useParentNodeId: (id: string | undefined) => string | undefined;
export declare const useRootTriggerId: () => string;
export declare const useIsAgentLoop: (id?: string) => boolean;
export declare const useIsWithinAgenticLoop: (id?: string) => boolean;
export declare const useHasUpstreamAgenticLoop: (upstreamNodes: string[]) => boolean;
export declare const useAgentOperations: () => string[];
export declare const useUriForAgentChat: (nodeId?: string) => string | undefined;
export declare const useAgentLastOperations: (agentOperations: string[]) => Record<string, any>;
export declare const getAgentFromCondition: (state: WorkflowState, nodeId: string) => string | undefined;
export declare const useAllAgentIds: () => string[];
export declare const useHandoffEdges: () => WorkflowEdge[];
export declare const useHandoffActionsForAgent: (agentId: string) => any[];
