import { EmptyContent } from '../emptycontent';
import React from 'react';
import ShallowRenderer from 'react-test-renderer/shallow';
import { describe, vi, beforeEach, afterEach, beforeAll, afterAll, it, test, expect } from 'vitest';
describe('lib/card/emptycontent', () => {
  let renderer: ShallowRenderer.ShallowRenderer;

  beforeEach(() => {
    renderer = ShallowRenderer.createRenderer();
  });

  afterEach(() => {
    renderer.unmount();
  });

  it('should render', () => {
    renderer.render(<EmptyContent />);

    const content = renderer.getRenderOutput();
    // Class names are now generated by makeStyles, so we just check the structure
    expect(content.type).toBe('div');

    const [icon, text]: any[] = React.Children.toArray(content.props.children);
    expect(icon.props).toEqual(
      expect.objectContaining({
        alt: '',
        role: 'presentation',
      })
    );
    expect(text.type).toBe('p');

    expect(text.props.children).toEqual('Please select a card to see the content');
  });
});
