import type { NodeStaticResults } from '../../actions/bjsworkflow/staticresults';
import type { ErrorInfo, NodeDependencies, NodeInputs, OperationMetadataState } from './operationMetadataSlice';
import { ErrorLevel } from './operationMetadataSlice';
import type { NodeOutputs } from '@microsoft/logic-apps-shared';
import { type ParameterInfo } from '@microsoft/designer-ui';
export declare const useOperationVisuals: (nodeId: string) => import("./operationMetadataSlice").OperationMetadata;
export declare const useOperationsVisuals: (nodesId: string[]) => {
    id: string;
    iconUri: string;
    brandColor: string;
    description?: string | undefined;
    summary?: string | undefined;
}[];
export declare const getNodeOperationData: (state: OperationMetadataState, nodeId: string) => {
    nodeInputs: NodeInputs | undefined;
    nodeOutputs: import("./operationMetadataSlice").NodeOutputs | undefined;
    nodeDependencies: NodeDependencies | undefined;
    operationMetadata: import("./operationMetadataSlice").OperationMetadata | undefined;
    settings: import("../../actions/bjsworkflow/settings").Settings | undefined;
    staticResult: NodeStaticResults | undefined;
    actionMetadata: any;
    repetitionInfo: import("../../utils/parameters/helper").RepetitionContext | undefined;
};
export declare const getOperationInputParameters: (nodeInputs: NodeInputs) => ParameterInfo[];
export declare const useOperationInputParameters: (nodeId: string) => ParameterInfo[];
export declare const useOperationParameterByName: (nodeId: string, parameterName: string) => ParameterInfo | undefined;
export declare const useOperationErrorInfo: (nodeId: string) => ErrorInfo | undefined;
export declare const useOperationDynamicInputsError: (nodeId: string | undefined) => string | undefined;
export declare const useAllConnectionErrors: () => Record<string, string>;
export declare const useOperationsInputParameters: () => Record<string, NodeInputs>;
export declare const useSecureInputsOutputs: (nodeId: string) => boolean;
export declare const useParameterStaticResult: (nodeId: string) => NodeStaticResults | undefined;
export declare const useRawInputParameters: (nodeId: string) => NodeInputs | undefined;
export declare const useRawOutputParameters: (nodeId: string) => NodeOutputs | undefined;
export declare const useDependencies: (nodeId: string) => NodeDependencies;
interface TokenDependencies {
    dependencies: Set<string>;
    loopSources: Set<string>;
}
export declare const useTokenDependencies: (nodeId: string) => TokenDependencies;
export declare const useNodesTokenDependencies: (nodes: Set<string>) => Record<string, Set<string>>;
export declare const useAllOperationErrors: () => Record<string, Record<ErrorLevel, ErrorInfo | undefined>>;
export declare const useParameterValidationErrors: (nodeId: string) => (string | undefined)[];
export declare const useNodesInitialized: () => boolean;
export declare const useNodesAndDynamicDataInitialized: () => boolean;
export declare const useIsNodeLoadingDynamicData: (nodeId: string) => boolean;
export declare const useBrandColor: (nodeId: string) => string;
export declare const useIconUri: (nodeId: string) => string;
export declare const useAllIcons: () => Record<string, string>;
export declare const useNodeConnectorId: (nodeId: string) => string | undefined;
export {};
