export const operation = {
  tags: ['Twitter'],
  summary: 'Search tweets',
  description: 'This operation gets a list of relevant tweets matching the search query.',
  operationId: 'SearchTweet',
  consumes: [],
  produces: ['application/json', 'text/json', 'application/xml', 'text/xml'],
  parameters: [
    {
      name: 'connectionId',
      in: 'path',
      required: true,
      type: 'string',
      'x-ms-visibility': 'internal',
    },
    {
      name: 'searchQuery',
      in: 'query',
      description: 'Search term like "happy hour", #haiku, love OR hate',
      required: true,
      'x-ms-summary': 'Search text',
      type: 'string',
    },
    {
      name: 'maxResults',
      in: 'query',
      description: 'Maximum number of tweets to return',
      required: false,
      'x-ms-summary': 'Maximum results',
      'x-ms-visibility': 'advanced',
      type: 'integer',
      format: 'int32',
      default: 20,
    },
    {
      name: 'sinceId',
      in: 'query',
      description: 'Return tweets after the specified tweet ID',
      required: false,
      'x-ms-summary': 'sinceId',
      'x-ms-visibility': 'advanced',
      type: 'string',
    },
  ],
  responses: {
    '200': {
      description: 'OK',
      schema: {
        type: 'array',
        items: {
          description: 'Representation of Tweet Object',
          required: ['TweetText', 'RetweetCount', 'TweetedBy'],
          type: 'object',
          properties: {
            TweetText: {
              description: 'Text content of the tweet',
              type: 'string',
              'x-ms-summary': 'Tweet text',
            },
            TweetId: {
              description: 'Id of the tweet',
              type: 'string',
              'x-ms-summary': 'Tweet id',
              'x-ms-visibility': 'advanced',
            },
            CreatedAt: {
              description: 'Time at which the tweet was posted',
              type: 'string',
              'x-ms-summary': 'Created at',
              'x-ms-visibility': 'internal',
            },
            CreatedAtIso: {
              description: 'Time at which the tweet was posted',
              type: 'string',
              'x-ms-summary': 'Created at',
              'x-ms-visibility': 'advanced',
            },
            RetweetCount: {
              format: 'int32',
              description: 'Total number of re-tweets for the tweet',
              type: 'integer',
              'x-ms-summary': 'Retweet count',
            },
            TweetedBy: {
              description: 'Name of the user who has posted the tweet',
              type: 'string',
              'x-ms-summary': 'Tweeted by',
            },
            MediaUrls: {
              description: 'Url of the media posted along with the tweet',
              type: 'array',
              items: {
                type: 'string',
              },
              'x-ms-summary': 'Media urls',
            },
            TweetLanguageCode: {
              description: 'Language code of the tweet',
              type: 'string',
              'x-ms-summary': 'Tweet language',
              'x-ms-visibility': 'advanced',
            },
            TweetInReplyToUserId: {
              description: 'User Id of the author of the tweet that the current tweet is a reply to',
              type: 'string',
              'x-ms-summary': 'in_reply_to_user_id',
              'x-ms-visibility': 'advanced',
            },
            Favorited: {
              description: 'Indicates whether the tweet is marked as favorited or not',
              type: 'boolean',
              'x-ms-visibility': 'advanced',
            },
            UserMentions: {
              description: 'List of users mentioned in the tweet',
              type: 'array',
              items: {
                description: 'Details for mentioned users',
                required: ['Id'],
                type: 'object',
                properties: {
                  Id: {
                    format: 'int64',
                    description: 'Twitter Id of the user',
                    type: 'integer',
                    'x-ms-summary': 'Mentioned user id',
                    'x-ms-visibility': 'advanced',
                  },
                  FullName: {
                    description: 'Full name of the user',
                    type: 'string',
                    'x-ms-summary': 'Mentioned user full name',
                    'x-ms-visibility': 'advanced',
                  },
                  UserName: {
                    description: 'Screen name of the user',
                    type: 'string',
                    'x-ms-summary': 'Mentioned user name',
                    'x-ms-visibility': 'advanced',
                  },
                },
              },
              'x-ms-summary': 'User mentions',
              'x-ms-visibility': 'advanced',
            },
            OriginalTweet: {
              description: 'Representation of original tweet object',
              required: ['TweetText', 'RetweetCount', 'TweetedBy'],
              type: 'object',
              properties: {
                TweetText: {
                  description: 'Text content of the original retrieved tweet',
                  type: 'string',
                  'x-ms-summary': 'Original tweet text',
                  'x-ms-visibility': 'advanced',
                },
                TweetId: {
                  description: 'Id of the original tweet',
                  type: 'string',
                  'x-ms-summary': 'Original tweet id',
                  'x-ms-visibility': 'advanced',
                },
                CreatedAt: {
                  description: 'Time at which original tweet was posted',
                  type: 'string',
                  'x-ms-summary': 'Original tweet created at',
                  'x-ms-visibility': 'internal',
                },
                CreatedAtIso: {
                  description: 'Time at which original tweet was posted',
                  type: 'string',
                  'x-ms-summary': 'Original tweet created at',
                  'x-ms-visibility': 'advanced',
                },
                RetweetCount: {
                  format: 'int32',
                  description: 'Total number of re-tweets for this original tweet',
                  type: 'integer',
                  'x-ms-summary': 'Original tweet retweet count',
                  'x-ms-visibility': 'advanced',
                },
                TweetedBy: {
                  description: 'User name of the person who posted the original tweet',
                  type: 'string',
                  'x-ms-summary': 'Original tweet tweeted by',
                  'x-ms-visibility': 'advanced',
                },
                MediaUrls: {
                  description: 'Url of the media posted along with the original tweet',
                  type: 'array',
                  items: {
                    type: 'string',
                  },
                  'x-ms-summary': 'Original tweet media urls',
                  'x-ms-visibility': 'advanced',
                },
                TweetLanguageCode: {
                  description: 'Language code for the original tweet',
                  type: 'string',
                  'x-ms-summary': 'Original tweet language',
                  'x-ms-visibility': 'advanced',
                },
                TweetInReplyToUserId: {
                  description: 'User Id of the author of the tweet that the current original tweet is a reply to',
                  type: 'string',
                  'x-ms-summary': 'Original tweet in_reply_to_user_id',
                  'x-ms-visibility': 'advanced',
                },
                Favorited: {
                  description: 'Indicates whether the original tweet is marked as favorited',
                  type: 'boolean',
                  'x-ms-summary': 'Original tweet favorited',
                  'x-ms-visibility': 'advanced',
                },
                UserMentions: {
                  description: 'The list of user mentions',
                  type: 'array',
                  items: {
                    description:
                      'The user mentions model. This class contains the details about the screen names extracted from the tweet.',
                    required: ['Id'],
                    type: 'object',
                    properties: {
                      Id: {
                        format: 'int64',
                        description: 'Twitter Id of the user',
                        type: 'integer',
                        'x-ms-summary': 'Original tweet mentioned user id',
                        'x-ms-visibility': 'advanced',
                      },
                      FullName: {
                        description: 'Full name of the user',
                        type: 'string',
                        'x-ms-summary': 'Original tweet mentioned user full name',
                        'x-ms-visibility': 'advanced',
                      },
                      UserName: {
                        description: 'Screen name of the user',
                        type: 'string',
                        'x-ms-summary': 'Original tweet mentioned user name',
                        'x-ms-visibility': 'advanced',
                      },
                    },
                  },
                  'x-ms-summary': 'Original tweet user mentions',
                  'x-ms-visibility': 'advanced',
                },
                UserDetails: {
                  description: "Representation of a Twitter User's Details",
                  required: ['FullName', 'Location', 'UserName', 'Description'],
                  type: 'object',
                  properties: {
                    FullName: {
                      description: 'Name of the user',
                      type: 'string',
                      'x-ms-summary': 'Original tweet user full name',
                      'x-ms-visibility': 'advanced',
                    },
                    Location: {
                      description: 'Location of the user',
                      type: 'string',
                      'x-ms-summary': 'Original tweet user Location',
                      'x-ms-visibility': 'advanced',
                    },
                    Id: {
                      format: 'int64',
                      description: 'Twitter Id of the user',
                      type: 'integer',
                      'x-ms-summary': 'Original tweet user id',
                      'x-ms-visibility': 'advanced',
                    },
                    UserName: {
                      description: 'Screen name of the user',
                      type: 'string',
                      'x-ms-summary': 'Original tweet user name',
                      'x-ms-visibility': 'advanced',
                    },
                    FollowersCount: {
                      format: 'int64',
                      description: 'Number of followers',
                      type: 'integer',
                      'x-ms-summary': 'Original tweet user followers count',
                      'x-ms-visibility': 'advanced',
                    },
                    Description: {
                      description: 'User description',
                      type: 'string',
                      'x-ms-summary': 'Original tweet user Description',
                      'x-ms-visibility': 'advanced',
                    },
                    StatusesCount: {
                      format: 'int64',
                      description: 'User status count',
                      type: 'integer',
                      'x-ms-summary': 'Original tweet user statuses count',
                      'x-ms-visibility': 'advanced',
                    },
                    FriendsCount: {
                      format: 'int64',
                      description: 'Number of friends',
                      type: 'integer',
                      'x-ms-summary': 'Original tweet user friends count',
                      'x-ms-visibility': 'advanced',
                    },
                    FavouritesCount: {
                      format: 'int64',
                      description: 'Number of tweets that the user has favorited',
                      type: 'integer',
                      'x-ms-summary': 'Original tweet user favourites count',
                      'x-ms-visibility': 'advanced',
                    },
                    ProfileImageUrl: {
                      description: 'Url of the profile image',
                      type: 'string',
                      'x-ms-summary': 'Original tweet user profile image url',
                      'x-ms-visibility': 'advanced',
                    },
                  },
                },
              },
            },
            UserDetails: {
              description: 'Twitter user details',
              required: ['FullName', 'Location', 'UserName', 'Description'],
              type: 'object',
              properties: {
                FullName: {
                  description: 'Name of the user',
                  type: 'string',
                  'x-ms-summary': 'Name',
                },
                Location: {
                  description: 'Location of the user',
                  type: 'string',
                  'x-ms-summary': 'Location',
                },
                Id: {
                  format: 'int64',
                  description: 'Twitter Id of the user',
                  type: 'integer',
                  'x-ms-summary': 'User id',
                  'x-ms-visibility': 'advanced',
                },
                UserName: {
                  description: 'Screen name of the user',
                  type: 'string',
                  'x-ms-summary': 'User name',
                },
                FollowersCount: {
                  format: 'int64',
                  description: 'Number of followers',
                  type: 'integer',
                  'x-ms-summary': 'Followers count',
                  'x-ms-visibility': 'advanced',
                },
                Description: {
                  description: 'User description',
                  type: 'string',
                  'x-ms-summary': 'Description',
                },
                StatusesCount: {
                  format: 'int64',
                  description: 'User status count',
                  type: 'integer',
                  'x-ms-summary': 'Statuses count',
                  'x-ms-visibility': 'advanced',
                },
                FriendsCount: {
                  format: 'int64',
                  description: 'Number of friends',
                  type: 'integer',
                  'x-ms-summary': 'Friends count',
                  'x-ms-visibility': 'advanced',
                },
                FavouritesCount: {
                  format: 'int64',
                  description: 'Number of tweets that the user has favorited',
                  type: 'integer',
                  'x-ms-summary': 'Favourites count',
                  'x-ms-visibility': 'advanced',
                },
                ProfileImageUrl: {
                  description: 'Url of the profile image',
                  type: 'string',
                  'x-ms-summary': 'Profile image url',
                  'x-ms-visibility': 'advanced',
                },
              },
            },
          },
        },
      },
    },
    '400': {
      description: 'Bad Request',
    },
    '401': {
      description: 'Unauthorized',
    },
    '403': {
      description: 'Forbidden',
    },
    '404': {
      description: 'Not Found',
    },
    '500': {
      description: 'Internal Server Error',
    },
    default: {
      description: 'Operation Failed.',
    },
  },
  deprecated: false,
  'x-ms-visibility': 'advanced',
  'x-ms-path': '/{connectionId}/searchtweets',
  'x-ms-method': 'get',
  'x-ms-base-path': '/apim/twitter',
};

export const parameters = {
  searchQuery: {
    key: 'query.$',
    description: 'Search term like "happy hour", #haiku, love OR hate',
    in: 'query',
    name: 'searchQuery',
    required: true,
    summary: 'Search text',
    type: 'string',
  },
  maxResults: {
    key: 'query.$',
    default: 20,
    description: 'Maximum number of tweets to return',
    format: 'int32',
    in: 'query',
    name: 'maxResults',
    required: false,
    summary: 'Maximum results',
    type: 'integer',
    visibility: 'advanced',
  },
  sinceId: {
    key: 'query.$',
    description: 'Return tweets after the specified tweet ID',
    in: 'query',
    name: 'sinceId',
    required: false,
    summary: 'sinceId',
    type: 'string',
    visibility: 'advanced',
  },
};
