import type { ConnectionReference, ConnectionReferences } from '../../../common/models/workflow';
import type { ConnectionsStoreState } from '../../state/connection/connectionSlice';
import type { NodeOperation } from '../../state/operation/operationMetadataSlice';
import { ConnectionType } from '@microsoft/logic-apps-shared';
import type { AssistedConnectionProps } from '@microsoft/designer-ui';
import type { Connection, ConnectionParameterSets, Connector, ManagedIdentity, OperationManifest } from '@microsoft/logic-apps-shared';
import type { UpdateConnectionPayload } from '../../../core/actions/bjsworkflow/connections';
export declare function getConnectionId(state: ConnectionsStoreState, nodeId: string): string;
export declare function getConnectionReference(state: ConnectionsStoreState, nodeId: string): ConnectionReference;
export declare const mockInvalidConnectionReference: ConnectionReference;
export declare const mockEmptyConnectionReference: ConnectionReference;
export declare function isConnectionValid(connection: Connection): boolean;
export declare function isConnectionReferenceValid(operationInfo: NodeOperation, reference: ConnectionReference | undefined): Promise<boolean>;
export declare function getExistingReferenceKey(allReferences: ConnectionReferences, connectionData: Omit<UpdateConnectionPayload, 'nodeId'>): string | undefined;
export declare function getAssistedConnectionProps(connector: Connector, manifest?: OperationManifest): AssistedConnectionProps | undefined;
export declare function getConnectionParametersForAzureConnection(connectionType?: ConnectionType, selectedSubResource?: any, parameterValues?: Record<string, any>, isMultiAuthConnection?: boolean): Promise<any>;
export declare function getSupportedParameterSets(parameterSets: ConnectionParameterSets | undefined, operationType: string, connectorCapabilities: string[] | undefined): ConnectionParameterSets | undefined;
export declare function isIdentityPresentInLogicApp(identity: string, managedIdentity: ManagedIdentity | undefined): boolean;
export declare function isConnectionMultiAuthManagedIdentityType(connection?: Connection | null, connector?: Connector): boolean;
export declare function isConnectionSingleAuthManagedIdentityType(connection: Connection): boolean;
