import type { DataMapSchema } from '@microsoft/logic-apps-shared';

const SourceSchemaXsd: DataMapSchema = {
  name: 'Source.xsd',
  type: 'XML',
  targetNamespace: 'http://tempuri.org/source.xsd',
  namespaces: {
    ns0: 'http://tempuri.org/source.xsd',
    xs: 'http://www.w3.org/2001/XMLSchema',
  },
  schemaTreeRoot: {
    key: '/ns0:Root',
    name: 'Root',
    type: 'Complex',
    properties: 'None',
    children: [
      {
        key: '/ns0:Root/DirectTranslation',
        name: 'DirectTranslation',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/DirectTranslation/EmployeeID',
            name: 'EmployeeID',
            type: 'Decimal',
            properties: 'None',
            qName: 'EmployeeID',
            children: [],
          },
          {
            key: '/ns0:Root/DirectTranslation/EmployeeName',
            name: 'EmployeeName',
            type: 'String',
            properties: 'None',
            qName: 'EmployeeName',
            children: [],
          },
        ],
        qName: 'DirectTranslation',
      },
      {
        key: '/ns0:Root/DataTranslation',
        name: 'DataTranslation',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/DataTranslation/Employee',
            name: 'Employee',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/DataTranslation/Employee/FirstName',
                name: 'FirstName',
                type: 'String',
                properties: 'None',
                qName: 'FirstName',
                children: [],
              },
              {
                key: '/ns0:Root/DataTranslation/Employee/LastName',
                name: 'LastName',
                type: 'String',
                properties: 'None',
                qName: 'LastName',
                children: [],
              },
              {
                key: '/ns0:Root/DataTranslation/Employee/EmploymentStatus',
                name: 'EmploymentStatus',
                type: 'Bool',
                properties: 'None',
                qName: 'EmploymentStatus',
                children: [],
              },
            ],
            qName: 'Employee',
          },
        ],
        qName: 'DataTranslation',
      },
      {
        key: '/ns0:Root/CumulativeExpression',
        name: 'CumulativeExpression',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/CumulativeExpression/Population',
            name: 'Population',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/CumulativeExpression/Population/State',
                name: 'State',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/CumulativeExpression/Population/State/Name',
                    name: 'Name',
                    type: 'String',
                    properties: 'None',
                    qName: 'Name',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/CumulativeExpression/Population/State/County',
                    name: 'County',
                    type: 'Complex',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/County/Name',
                        name: 'Name',
                        type: 'String',
                        properties: 'None',
                        qName: 'Name',
                        children: [],
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                        name: 'Person',
                        type: 'Complex',
                        properties: 'Repeating',
                        children: [
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Name',
                            name: 'Name',
                            type: 'String',
                            properties: 'None',
                            qName: 'Name',
                            children: [],
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Age',
                            name: 'Age',
                            type: 'String',
                            properties: 'None',
                            qName: 'Age',
                            children: [],
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                            name: 'Sex',
                            type: 'Complex',
                            properties: 'None',
                            children: [
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Male',
                                name: 'Male',
                                type: 'Bool',
                                properties: 'None',
                                qName: 'Male',
                                children: [],
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Female',
                                name: 'Female',
                                type: 'Bool',
                                properties: 'None',
                                qName: 'Female',
                                children: [],
                              },
                            ],
                            qName: 'Sex',
                          },
                        ],
                        qName: 'Person',
                      },
                    ],
                    qName: 'County',
                  },
                ],
                qName: 'State',
              },
            ],
            qName: 'Population',
          },
        ],
        qName: 'CumulativeExpression',
      },
      {
        key: '/ns0:Root/ConditionalMapping',
        name: 'ConditionalMapping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/ConditionalMapping/ItemPrice',
            name: 'ItemPrice',
            type: 'Decimal',
            properties: 'None',
            qName: 'ItemPrice',
            children: [],
          },
          {
            key: '/ns0:Root/ConditionalMapping/ItemQuantity',
            name: 'ItemQuantity',
            type: 'Decimal',
            properties: 'None',
            qName: 'ItemQuantity',
            children: [],
          },
        ],
        qName: 'ConditionalMapping',
      },
      {
        key: '/ns0:Root/Looping',
        name: 'Looping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            type: 'Complex',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                type: 'String',
                properties: 'None',
                qName: 'TelephoneNumber',
                children: [],
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                type: 'String',
                properties: 'None',
                qName: 'Name',
                children: [],
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                type: 'Decimal',
                properties: 'None',
                qName: 'Salary',
                children: [],
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                type: 'String',
                properties: 'None',
                qName: 'Country',
                children: [],
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                type: 'DateTime',
                properties: 'None',
                qName: 'Dat_of_Birth',
                children: [],
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                type: 'String',
                properties: 'None',
                qName: 'Address',
                children: [],
              },
            ],
            qName: 'Employee',
          },
          {
            key: '/ns0:Root/Looping/VehicleTrips',
            name: 'VehicleTrips',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                name: 'Vehicle',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleID',
                    name: 'VehicleID',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleID',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleRegistration',
                    name: 'VehicleRegistration',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleRegistration',
                    children: [],
                  },
                ],
                qName: 'Vehicle',
              },
              {
                key: '/ns0:Root/Looping/VehicleTrips/Trips',
                name: 'Trips',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/VehicleId',
                    name: 'VehicleId',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleId',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/Distance',
                    name: 'Distance',
                    type: 'Decimal',
                    properties: 'None',
                    qName: 'Distance',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/Duration',
                    name: 'Duration',
                    type: 'Decimal',
                    properties: 'None',
                    qName: 'Duration',
                    children: [],
                  },
                ],
                qName: 'Trips',
              },
            ],
            qName: 'VehicleTrips',
          },
        ],
        qName: 'Looping',
      },
      {
        key: '/ns0:Root/ConditionalLooping',
        name: 'ConditionalLooping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
            name: 'FlatterCatalog',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                name: 'Product',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Name',
                    name: 'Name',
                    type: 'String',
                    properties: 'None',
                    qName: 'Name',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/SKU',
                    name: 'SKU',
                    type: 'String',
                    properties: 'None',
                    qName: 'SKU',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Price',
                    name: 'Price',
                    type: 'String',
                    properties: 'None',
                    qName: 'Price',
                    children: [],
                  },
                ],
                qName: 'ns0:Product',
              },
            ],
            qName: 'FlatterCatalog',
          },
        ],
        qName: 'ConditionalLooping',
      },
      {
        key: '/ns0:Root/LoopingWithIndex',
        name: 'LoopingWithIndex',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/LoopingWithIndex/WeatherReport',
            name: 'WeatherReport',
            type: 'Complex',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Pressure',
                name: 'Pressure',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@Pressure',
                children: [],
              },
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@WindSpeed',
                name: 'WindSpeed',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@WindSpeed',
                children: [],
              },
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Temperature',
                name: 'Temperature',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@Temperature',
                children: [],
              },
            ],
            qName: 'WeatherReport',
          },
        ],
        qName: 'LoopingWithIndex',
      },
      {
        key: '/ns0:Root/NameValueTransforms',
        name: 'NameValueTransforms',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/NameValueTransforms/Catalog',
            name: 'Catalog',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                name: 'Product',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                    name: 'Field',
                    type: 'Complex',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Name',
                        name: 'Name',
                        type: 'String',
                        properties: 'None',
                        qName: 'Name',
                        children: [],
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Value',
                        name: 'Value',
                        type: 'String',
                        properties: 'None',
                        qName: 'Value',
                        children: [],
                      },
                    ],
                    qName: 'Field',
                  },
                ],
                qName: 'Product',
              },
            ],
            qName: 'Catalog',
          },
          {
            key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
            name: 'PurchaseOrderStatus',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ShipperName',
                name: 'ShipperName',
                type: 'String',
                properties: 'None',
                qName: 'ShipperName',
                children: [],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ServiceLevel',
                name: 'ServiceLevel',
                type: 'String',
                properties: 'None',
                qName: 'ServiceLevel',
                children: [],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/DateShipped',
                name: 'DateShipped',
                type: 'String',
                properties: 'None',
                qName: 'DateShipped',
                children: [],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                name: 'LineItem',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/ItemNumber',
                    name: 'ItemNumber',
                    type: 'String',
                    properties: 'None',
                    qName: 'ItemNumber',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityOrdered',
                    name: 'QuantityOrdered',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityOrdered',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityShipped',
                    name: 'QuantityShipped',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityShipped',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityBackordered',
                    name: 'QuantityBackordered',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityBackordered',
                    children: [],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityCancelled',
                    name: 'QuantityCancelled',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityCancelled',
                    children: [],
                  },
                ],
                qName: 'ns0:LineItem',
              },
            ],
            qName: 'PurchaseOrderStatus',
          },
        ],
        qName: 'NameValueTransforms',
      },
    ],
    qName: 'ns0:Root',
  },
};

export default SourceSchemaXsd;
