import type { DataMapSchema } from '@microsoft/logic-apps-shared';

const SourceSchemaJson: DataMapSchema = {
  name: 'SourceSchemaJson.json',
  type: 'JSON',
  targetNamespace: '',
  schemaTreeRoot: {
    key: '/root',
    name: 'root',
    type: 'Object',
    properties: 'None',
    children: [
      {
        key: '/root/flowVars',
        name: 'flowVars',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/flowVars/username',
            name: 'username',
            type: 'String',
            properties: 'None',
            qName: 'username',
            children: [],
          },
        ],
        qName: 'flowVars',
      },
      {
        key: '/root/customerNumber',
        name: 'customerNumber',
        type: 'String',
        properties: 'None',
        qName: 'customerNumber',
        children: [],
      },
      {
        key: '/root/Count',
        name: 'Count',
        type: 'Integer',
        properties: 'None',
        qName: 'Count',
        children: [],
      },
      {
        key: '/root/Count1',
        name: 'Count1',
        type: 'Integer',
        properties: 'None',
        qName: 'Count1',
        children: [],
      },
      {
        key: '/root/OrderNo',
        name: 'OrderNo',
        type: 'String',
        properties: 'None',
        qName: 'OrderNo',
        children: [],
      },
      {
        key: '/root/Num',
        name: 'Num',
        type: 'Integer',
        properties: 'None',
        qName: 'Num',
        children: [],
      },
      {
        key: '/root/Num1',
        name: 'Num1',
        type: 'Integer',
        properties: 'None',
        qName: 'Num1',
        children: [],
      },
      {
        key: '/root/Num2',
        name: 'Num2',
        type: 'Integer',
        properties: 'None',
        qName: 'Num2',
        children: [],
      },
      {
        key: '/root/Nums',
        name: 'Nums',
        type: 'Array',
        properties: 'None',
        children: [
          {
            key: '/root/Nums/*',
            name: '<ArrayItem>',
            type: 'Object',
            properties: 'Repeating, ArrayItem',
            children: [
              {
                key: '/root/Nums/*/Num',
                name: 'Num',
                type: 'Integer',
                properties: 'None',
                qName: 'Num',
                children: [],
              },
            ],
            qName: '<ArrayItem>',
          },
        ],
        qName: 'Nums',
      },
      {
        key: '/root/Strings',
        name: 'Strings',
        type: 'Array',
        properties: 'None',
        children: [
          {
            key: '/root/Strings/*',
            name: '<ArrayItem>',
            type: 'Object',
            properties: 'Repeating, ArrayItem',
            children: [
              {
                key: '/root/Strings/*/String',
                name: 'String',
                type: 'String',
                properties: 'None',
                qName: 'String',
                children: [],
              },
            ],
            qName: '<ArrayItem>',
          },
        ],
        qName: 'Strings',
      },
      {
        key: '/root/ConditionalNode',
        name: 'ConditionalNode',
        type: 'String',
        properties: 'None',
        qName: 'ConditionalNode',
        children: [],
      },
      {
        key: '/root/salesOrg',
        name: 'salesOrg',
        type: 'String',
        properties: 'None',
        qName: 'salesOrg',
        children: [],
      },
      {
        key: '/root/shipDate',
        name: 'shipDate',
        type: 'String',
        properties: 'None',
        qName: 'shipDate',
        children: [],
      },
      {
        key: '/root/Num3',
        name: 'Num3',
        type: 'Decimal',
        properties: 'None',
        qName: 'Num3',
        children: [],
      },
      {
        key: '/root/Decimal',
        name: 'Decimal',
        type: 'Decimal',
        properties: 'None',
        qName: 'Decimal',
        children: [],
      },
      {
        key: '/root/arrayOfArray',
        name: 'arrayOfArray',
        type: 'Array',
        properties: 'None',
        children: [
          {
            key: '/root/arrayOfArray/*',
            name: '<ArrayItem>',
            type: 'Array',
            properties: 'Repeating, ArrayItem',
            children: [
              {
                key: '/root/arrayOfArray/*/*',
                name: '<ArrayItem>',
                type: 'Integer',
                properties: 'Repeating, ArrayItem',
                qName: '<ArrayItem>',
                children: [],
              },
            ],
            qName: '<ArrayItem>',
          },
        ],
        qName: 'arrayOfArray',
      },
      {
        key: '/root/generalData',
        name: 'generalData',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/generalData/address',
            name: 'address',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/generalData/address/telephone',
                name: 'telephone',
                type: 'Array',
                properties: 'None',
                children: [
                  {
                    key: '/root/generalData/address/telephone/*',
                    name: '<ArrayItem>',
                    type: 'Object',
                    properties: 'Repeating, ArrayItem',
                    children: [
                      {
                        key: '/root/generalData/address/telephone/*/country',
                        name: 'country',
                        type: 'String',
                        properties: 'None',
                        qName: 'country',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/number',
                        name: 'number',
                        type: 'String',
                        properties: 'None',
                        qName: 'number',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/extension',
                        name: 'extension',
                        type: 'String',
                        properties: 'None',
                        qName: 'extension',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/preferred',
                        name: 'preferred',
                        type: 'String',
                        properties: 'None',
                        qName: 'preferred',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/type',
                        name: 'type',
                        type: 'String',
                        properties: 'None',
                        qName: 'type',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/topzip',
                        name: 'topzip',
                        type: 'String',
                        properties: 'None',
                        qName: 'topzip',
                        children: [],
                      },
                      {
                        key: '/root/generalData/address/telephone/*/zips',
                        name: 'zips',
                        type: 'Array',
                        properties: 'None',
                        children: [
                          {
                            key: '/root/generalData/address/telephone/*/zips/*',
                            name: '<ArrayItem>',
                            type: 'String',
                            properties: 'Repeating, ArrayItem',
                            qName: '<ArrayItem>',
                            children: [],
                          },
                        ],
                        qName: 'zips',
                      },
                    ],
                    qName: '<ArrayItem>',
                  },
                ],
                qName: 'telephone',
              },
            ],
            qName: 'address',
          },
          {
            key: '/root/generalData/contactPerson',
            name: 'contactPerson',
            type: 'Array',
            properties: 'None',
            children: [
              {
                key: '/root/generalData/contactPerson/*',
                name: '<ArrayItem>',
                type: 'Object',
                properties: 'Repeating, ArrayItem',
                children: [
                  {
                    key: '/root/generalData/contactPerson/*/firstName',
                    name: 'firstName',
                    type: 'String',
                    properties: 'None',
                    qName: 'firstName',
                    children: [],
                  },
                  {
                    key: '/root/generalData/contactPerson/*/name1',
                    name: 'name1',
                    type: 'String',
                    properties: 'None',
                    qName: 'name1',
                    children: [],
                  },
                  {
                    key: '/root/generalData/contactPerson/*/telephone',
                    name: 'telephone',
                    type: 'Array',
                    properties: 'None',
                    children: [
                      {
                        key: '/root/generalData/contactPerson/*/telephone/*',
                        name: '<ArrayItem>',
                        type: 'Object',
                        properties: 'Repeating, ArrayItem',
                        children: [
                          {
                            key: '/root/generalData/contactPerson/*/telephone/*/country',
                            name: 'country',
                            type: 'String',
                            properties: 'None',
                            qName: 'country',
                            children: [],
                          },
                          {
                            key: '/root/generalData/contactPerson/*/telephone/*/number',
                            name: 'number',
                            type: 'String',
                            properties: 'None',
                            qName: 'number',
                            children: [],
                          },
                        ],
                        qName: '<ArrayItem>',
                      },
                    ],
                    qName: 'telephone',
                  },
                  {
                    key: '/root/generalData/contactPerson/*/email',
                    name: 'email',
                    type: 'Array',
                    properties: 'None',
                    children: [
                      {
                        key: '/root/generalData/contactPerson/*/email/*',
                        name: '<ArrayItem>',
                        type: 'Object',
                        properties: 'Repeating, ArrayItem',
                        children: [
                          {
                            key: '/root/generalData/contactPerson/*/email/*/address',
                            name: 'address',
                            type: 'String',
                            properties: 'None',
                            qName: 'address',
                            children: [],
                          },
                          {
                            key: '/root/generalData/contactPerson/*/email/*/note',
                            name: 'note',
                            type: 'String',
                            properties: 'Optional',
                            qName: 'note',
                            children: [],
                          },
                        ],
                        qName: '<ArrayItem>',
                      },
                    ],
                    qName: 'email',
                  },
                ],
                qName: '<ArrayItem>',
              },
            ],
            qName: 'contactPerson',
          },
        ],
        qName: 'generalData',
      },
      {
        key: '/root/text',
        name: 'text',
        type: 'Array',
        properties: 'None',
        children: [
          {
            key: '/root/text/*',
            name: '<ArrayItem>',
            type: 'Object',
            properties: 'Repeating, ArrayItem',
            children: [
              {
                key: '/root/text/*/itemNumber',
                name: 'itemNumber',
                type: 'String',
                properties: 'None',
                qName: 'itemNumber',
                children: [],
              },
              {
                key: '/root/text/*/textId',
                name: 'textId',
                type: 'String',
                properties: 'Optional',
                qName: 'textId',
                children: [],
              },
            ],
            qName: '<ArrayItem>',
          },
        ],
        qName: 'text',
      },
      {
        key: '/root/leoData',
        name: 'leoData',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/leoData/routeOptimization',
            name: 'routeOptimization',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/leoData/routeOptimization/driver',
                name: 'driver',
                type: 'String',
                properties: 'None',
                qName: 'driver',
                children: [],
              },
            ],
            qName: 'routeOptimization',
          },
        ],
        qName: 'leoData',
      },
      {
        key: '/root/_-SCL_-OTC_GET_CUST_AML.Response',
        name: '_-SCL_-OTC_GET_CUST_AML.Response',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML',
            name: 'EX_I_AML',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML/item',
                name: 'item',
                type: 'Array',
                properties: 'None',
                children: [
                  {
                    key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML/item/*',
                    name: '<ArrayItem>',
                    type: 'Object',
                    properties: 'Repeating, ArrayItem',
                    children: [
                      {
                        key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML/item/*/MAKTX',
                        name: 'MAKTX',
                        type: 'String',
                        properties: 'None',
                        qName: 'MAKTX',
                        children: [],
                      },
                      {
                        key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML/item/*/MATNR',
                        name: 'MATNR',
                        type: 'String',
                        properties: 'None',
                        qName: 'MATNR',
                        children: [],
                      },
                      {
                        key: '/root/_-SCL_-OTC_GET_CUST_AML.Response/EX_I_AML/item/*/_-SCL_-BCAT',
                        name: '_-SCL_-BCAT',
                        type: 'String',
                        properties: 'None',
                        qName: '_-SCL_-BCAT',
                        children: [],
                      },
                    ],
                    qName: '<ArrayItem>',
                  },
                ],
                qName: 'item',
              },
            ],
            qName: 'EX_I_AML',
          },
        ],
        qName: '_-SCL_-OTC_GET_CUST_AML.Response',
      },
      {
        key: '/root/items',
        name: 'items',
        type: 'Array',
        properties: 'None',
        children: [
          {
            key: '/root/items/*',
            name: '<ArrayItem>',
            type: 'Object',
            properties: 'Repeating, ArrayItem',
            children: [
              {
                key: '/root/items/*/targetQuantity',
                name: 'targetQuantity',
                type: 'Integer',
                properties: 'None',
                qName: 'targetQuantity',
                children: [],
              },
              {
                key: '/root/items/*/conditionType',
                name: 'conditionType',
                type: 'String',
                properties: 'None',
                qName: 'conditionType',
                children: [],
              },
              {
                key: '/root/items/*/pricingDate',
                name: 'pricingDate',
                type: 'String',
                properties: 'None',
                qName: 'pricingDate',
                children: [],
              },
              {
                key: '/root/items/*/rate',
                name: 'rate',
                type: 'Decimal',
                properties: 'None',
                qName: 'rate',
                children: [],
              },
              {
                key: '/root/items/*/uom',
                name: 'uom',
                type: 'String',
                properties: 'None',
                qName: 'uom',
                children: [],
              },
              {
                key: '/root/items/*/value',
                name: 'value',
                type: 'Integer',
                properties: 'None',
                qName: 'value',
                children: [],
              },
              {
                key: '/root/items/*/currency',
                name: 'currency',
                type: 'String',
                properties: 'None',
                qName: 'currency',
                children: [],
              },
            ],
            qName: '<ArrayItem>',
          },
        ],
        qName: 'items',
      },
      {
        key: '/root/companyCode',
        name: 'companyCode',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/companyCode/accountManagement',
            name: 'accountManagement',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/companyCode/accountManagement/reconAcc',
                name: 'reconAcc',
                type: 'String',
                properties: 'None',
                qName: 'reconAcc',
                children: [],
              },
            ],
            qName: 'accountManagement',
          },
        ],
        qName: 'companyCode',
      },
      {
        key: '/root/SourceMadeUp',
        name: 'SourceMadeUp',
        type: 'Object',
        properties: 'None',
        children: [
          {
            key: '/root/SourceMadeUp/ManyManyArray',
            name: 'ManyManyArray',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/SourceMadeUp/ManyManyArray/*',
                name: '<ArrayItem>',
                type: 'Array',
                properties: 'Repeating, ArrayItem',
                children: [
                  {
                    key: '/root/SourceMadeUp/ManyManyArray/*/*',
                    name: '<ArrayItem>',
                    type: 'Array',
                    properties: 'Repeating, ArrayItem',
                    children: [
                      {
                        key: '/root/SourceMadeUp/ManyManyArray/*/*/SourceMadeUp_NeedAProp',
                        name: 'SourceMadeUp_NeedAProp',
                        type: 'Integer',
                        properties: 'None',
                        qName: 'SourceMadeUp_NeedAProp',
                        children: [],
                      },
                    ],
                    qName: '<ArrayItem>',
                  },
                ],
                qName: '<ArrayItem>',
              },
            ],
            qName: 'ManyManyArray',
          },
          {
            key: '/root/SourceMadeUp/ManySingleArray',
            name: 'ManySingleArray',
            type: 'Object',
            properties: 'None',
            children: [
              {
                key: '/root/SourceMadeUp/ManySingleArray/*',
                name: '<ArrayItem>',
                type: 'Array',
                properties: 'Repeating, ArrayItem',
                children: [
                  {
                    key: '/root/SourceMadeUp/ManySingleArray/*/*',
                    name: '<ArrayItem>',
                    type: 'Array',
                    properties: 'Repeating, ArrayItem',
                    children: [
                      {
                        key: '/root/SourceMadeUp/ManySingleArray/*/*/SourceMadeUp_NeedAProp',
                        name: 'SourceMadeUp_NeedAProp',
                        type: 'Integer',
                        properties: 'None',
                        qName: 'SourceMadeUp_NeedAProp',
                        children: [],
                      },
                    ],
                    qName: '<ArrayItem>',
                  },
                ],
                qName: '<ArrayItem>',
              },
            ],
            qName: 'ManySingleArray',
          },
        ],
        qName: 'SourceMadeUp',
      },
    ],
    qName: 'root',
  },
};

export default SourceSchemaJson;
