fileGroups:
  default:
    - '**/*'
  production:
    - '**/*'
    # - '!**/?(*.)+(spec|test).[jt]s?(x)?(.snap)'
    - '!tsconfig.spec.json'
    - '!jest.config.[jt]s'
  sharedGlobals:
    - /babel.config.json
