import type { DiscoveryOperation, DiscoveryResultTypes } from '@microsoft/logic-apps-shared';

export const almostAllBuiltInOperations: DiscoveryOperation<DiscoveryResultTypes>[] = [
  // result from this url https://management.azure.com/subscriptions/4201f397-837b-48ea-8943-980767f294ac/resourceGroups/LogicApps/providers/Microsoft.Web/sites/standarddacogbur/hostruntime/runtime/webhooks/workflow/api/management/operations?api-version=2018-11-01&workflowKind=Stateful&%24filter=
  {
    name: 'whenABlobIsAddedOrModified',
    id: 'whenABlobIsAddedOrModified',
    type: 'whenABlobIsAddedOrModified',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'When a blob is Added or Modified in Azure Storage',
      description: 'When a Blob is Added or Modified in Azure Storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      trigger: 'Single',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'blobExists',
    id: 'blobExists',
    type: 'blobExists',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Checks if Blob exists in Azure Storage',
      description: 'Checks if Blob exists in Azure Storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'deleteBlob',
    id: 'deleteBlob',
    type: 'deleteBlob',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Deletes a Blob from Azure Storage',
      description: 'Deletes a Blob from Azure Storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'readBlob',
    id: 'readBlob',
    type: 'readBlob',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Reads Blob Content from Azure Storage',
      description: 'Reads Blob Content from Azure Storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'uploadBlob',
    id: 'uploadBlob',
    type: 'uploadBlob',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Uploads a Blob to Azure Storage',
      description: 'Uploads a Blob to Azure Storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'getBlobSASUri',
    id: 'getBlobSASUri',
    type: 'getBlobSASUri',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Get SAS URI for given path of Azure Blob storage',
      description: 'Get SAS URI for given path of Azure Blob storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'getBlobMetadata',
    id: 'getBlobMetadata',
    type: 'getBlobMetadata',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Get blob metadata for given path of Azure Blob storage',
      description: 'Get blob metadata for given path of Azure Blob storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'getContainerMetadata',
    id: 'getContainerMetadata',
    type: 'getContainerMetadata',
    properties: {
      api: {
        id: '/serviceProviders/AzureBlob',
        type: 'ServiceProvider',
        name: 'AzureBlob',
        displayName: 'Azure Blob',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Azure Blob Storage.',
      },
      summary: 'Get container metadata for given path of Azure Blob storage',
      description: 'Get container metadata for given path of Azure Blob storage',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1443/1.0.1443.2341/azureblob/icon.png',
    },
  },
  {
    name: 'putMessage',
    id: 'putMessage',
    type: 'putMessage',
    properties: {
      api: {
        id: '/serviceProviders/azurequeues',
        type: 'ServiceProvider',
        name: 'azurequeues',
        displayName: 'Azure Queue',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Queue to send and receive messages.',
      },
      summary: 'Add a message to queue',
      description: 'Add a message to queue',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azurequeues',
      },
    },
  },
  {
    name: 'getMessages',
    id: 'getMessages',
    type: 'getMessages',
    properties: {
      api: {
        id: '/serviceProviders/azurequeues',
        type: 'ServiceProvider',
        name: 'azurequeues',
        displayName: 'Azure Queue',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Queue to send and receive messages.',
      },
      summary: 'Get Messages',
      description:
        'Get a specific set of messages from the queue. The messages will be hidden but remain on the queue until the delete action is used.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azurequeues',
      },
    },
  },
  {
    name: 'deleteMessage',
    id: 'deleteMessage',
    type: 'deleteMessage',
    properties: {
      api: {
        id: '/serviceProviders/azurequeues',
        type: 'ServiceProvider',
        name: 'azurequeues',
        displayName: 'Azure Queue',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Queue to send and receive messages.',
      },
      summary: 'Delete message',
      description: 'Delete a specific message from the queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azurequeues',
      },
    },
  },
  {
    name: 'putQueue',
    id: 'putQueue',
    type: 'putQueue',
    properties: {
      api: {
        id: '/serviceProviders/azurequeues',
        type: 'ServiceProvider',
        name: 'azurequeues',
        displayName: 'Azure Queue',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Queue to send and receive messages.',
      },
      summary: 'Create a new queue',
      description: 'Create a new queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azurequeues',
      },
    },
  },
  {
    name: 'createTable',
    id: 'createTable',
    type: 'createTable',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Create table',
      description: 'Creates a table in Azure Table Storage.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'listTables',
    id: 'listTables',
    type: 'listTables',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'List tables',
      description: 'Lists tables from Azure Table Storage.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'deleteTable',
    id: 'deleteTable',
    type: 'deleteTable',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Delete table',
      description: 'Deletes a table in Azure Table Storage.',
      visibility: 'NotSpecified',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'upsertEntity',
    id: 'upsertEntity',
    type: 'upsertEntity',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Insert or Update Entity',
      description: 'Inserts or updates an entity in the table.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'updateEntity',
    id: 'updateEntity',
    type: 'updateEntity',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Update Entity',
      description: 'Updates an entity in the table.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'deleteEntity',
    id: 'deleteEntity',
    type: 'deleteEntity',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Delete Entity',
      description: 'Deletes the entity in the table.',
      visibility: 'NotSpecified',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'getEntity',
    id: 'getEntity',
    type: 'getEntity',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Get Entity',
      description: 'Gets an entity in the table.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'queryEntities',
    id: 'queryEntities',
    type: 'queryEntities',
    properties: {
      api: {
        id: '/serviceProviders/azureTables',
        type: 'ServiceProvider',
        name: 'azureTables',
        displayName: 'Azure Table Storage',
        iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
        brandColor: '#804998',
        description: 'Connect to your Azure Table Storage to create, query and update, table entries and tables.',
      },
      summary: 'Query Entities',
      description: 'Queries the table for entities.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/azuretables/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/azureTables',
      },
    },
  },
  {
    name: 'whenADocumentIsCreatedOrModified',
    id: 'whenADocumentIsCreatedOrModified',
    type: 'whenADocumentIsCreatedOrModified',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'When an item is created or modified',
      description: 'When an item is created or modified.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      trigger: 'Batch',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'BulkCreateOrUpdateDocument',
    id: 'BulkCreateOrUpdateDocument',
    type: 'BulkCreateOrUpdateDocument',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Create or update many items in bulk',
      description: 'Create or update many items in bulk.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'testAnOperation',
    id: 'testAnOperation',
    type: 'testAnOperation',
    properties: {
      api: {
        id: '/serviceProviders/TestConnector',
        type: 'ServiceProvider',
        name: 'testAnOperationConnector',
        displayName: 'Test Connector',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'This is a test',
      },
      summary: 'Create or update many items in bulk',
      description: 'Create or update many items in bulk.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/TestConnector',
      },
    },
  },
  {
    name: 'CreateOrUpdateDocument',
    id: 'CreateOrUpdateDocument',
    type: 'CreateOrUpdateDocument',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Create or update item',
      description: 'Create or update item.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'DeleteDocument',
    id: 'DeleteDocument',
    type: 'DeleteDocument',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Delete an item',
      description: 'Delete an item.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'QueryDocuments',
    id: 'QueryDocuments',
    type: 'QueryDocuments',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Query items',
      description: 'Query items.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'ReadDocument',
    id: 'ReadDocument',
    type: 'ReadDocument',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Read an item',
      description: 'Read an item.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'PatchItem',
    id: 'PatchItem',
    type: 'PatchItem',
    properties: {
      api: {
        id: '/serviceProviders/AzureCosmosDB',
        type: 'ServiceProvider',
        name: 'AzureCosmosDB',
        displayName: 'Azure Cosmos DB',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
        brandColor: '#804998',
        description: 'Connect to Azure Cosmos DB to perform document CRUD operations and listen to change feed processor.',
      },
      summary: 'Patch an item',
      description: 'Patch an item.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#804998',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1393/1.0.1393.2131/documentdb/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/AzureCosmosDB',
      },
    },
  },
  {
    name: 'deleteRow',
    id: 'deleteRow',
    type: 'deleteRow',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Delete row',
      description: 'Delete row or rows.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'executeNonQuery',
    id: 'executeNonQuery',
    type: 'executeNonQuery',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Execute non-query',
      description: 'Execute a SQL command that does not return a result set.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'executeQuery',
    id: 'executeQuery',
    type: 'executeQuery',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Execute query',
      description: 'Execute a SQL query.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'getTables',
    id: 'getTables',
    type: 'getTables',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'DB2 tables',
      description: 'Return tables in DB2 schema.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'insertRow',
    id: 'insertRow',
    type: 'insertRow',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Insert row',
      description: 'Insert a row.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'storedProcedure',
    id: 'storedProcedure',
    type: 'storedProcedure',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Execute a stored procedure',
      description: 'Stored procedure',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'updateRow',
    id: 'updateRow',
    type: 'updateRow',
    properties: {
      api: {
        id: '/serviceProviders/DB2',
        type: 'ServiceProvider',
        name: 'DB2',
        displayName: 'DB2',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The DB2 connector provides an API to work with DB2 databases.',
      },
      summary: 'Update rows',
      description: 'Update row or rows.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/DB2',
      },
    },
  },
  {
    name: 'receiveEvents',
    id: 'receiveEvents',
    type: 'receiveEvents',
    properties: {
      api: {
        id: '/serviceProviders/eventHub',
        type: 'ServiceProvider',
        name: 'eventHub',
        displayName: 'Event Hubs',
        iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Event Hubs to send and receive events.',
      },
      summary: 'When events are available in Event hub',
      description: 'When events are available in Event Hub.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      trigger: 'Batch',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'sendEvent',
    id: 'sendEvent',
    type: 'sendEvent',
    properties: {
      api: {
        id: '/serviceProviders/eventHub',
        type: 'ServiceProvider',
        name: 'eventHub',
        displayName: 'Event Hubs',
        iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Event Hubs to send and receive events.',
      },
      summary: 'Send Event',
      description: 'Connect to Azure Event Hubs to send event.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'sendEvents',
    id: 'sendEvents',
    type: 'sendEvents',
    properties: {
      api: {
        id: '/serviceProviders/eventHub',
        type: 'ServiceProvider',
        name: 'eventHub',
        displayName: 'Event Hubs',
        iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Event Hubs to send and receive events.',
      },
      summary: 'Send Multiple Events',
      description: 'Connect to Azure Event Hubs to send events.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/eventhubs/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'whenFtpFilesAreAddedOrModified',
    id: 'whenFtpFilesAreAddedOrModified',
    type: 'whenFtpFilesAreAddedOrModified',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'When a file is added or updated',
      description: 'This trigger fires when a new file is created or an existing file is updated in the watch folder.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      operationKind: 'Polling',
      trigger: 'Batch',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'getFtpFileContent',
    id: 'getFtpFileContent',
    type: 'getFtpFileContent',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'Get File Content',
      description: 'The file content.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'getFileMetadata',
    id: 'getFileMetadata',
    type: 'getFileMetadata',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'Get the file metadata',
      description: 'The metadata of the file',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'createFile',
    id: 'createFile',
    type: 'createFile',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'Create file',
      description: 'Creates a file on the FTP server. The file is overwritten if already present.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'updateFile',
    id: 'updateFile',
    type: 'updateFile',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'Update file',
      description: 'Updates a file on the FTP server.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'deleteFtpFile',
    id: 'deleteFtpFile',
    type: 'deleteFtpFile',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'Delete file',
      description: 'Deletes a file on the FTP server.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'listFilesInFolder',
    id: 'listFilesInFolder',
    type: 'listFilesInFolder',
    properties: {
      api: {
        id: '/serviceProviders/Ftp',
        type: 'ServiceProvider',
        name: 'Ftp',
        displayName: 'FTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
        brandColor: '#ff8a00',
        description: 'Connect to a FTP server to receive file updates.',
      },
      summary: 'List files and subfolders in a folder',
      description: 'Lists files and subfolders in a folder',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#ff8a00',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1538/1.0.1538.2619/ftp/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Ftp',
      },
    },
  },
  {
    name: 'generateFileContents',
    id: 'generateFileContents',
    type: 'generateFileContents',
    properties: {
      api: {
        id: '/serviceProviders/hostfile',
        type: 'ServiceProvider',
        name: 'hostfile',
        displayName: 'IBM Host File',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The IBM Host File connector provides an API to work with off-line files of IBM origin.',
      },
      summary: 'Generate Host File Contents',
      description: 'Generate contents of a file in IBM formats.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/hostfile',
      },
    },
  },
  {
    name: 'parseFileContents',
    id: 'parseFileContents',
    type: 'parseFileContents',
    properties: {
      api: {
        id: '/serviceProviders/hostfile',
        type: 'ServiceProvider',
        name: 'hostfile',
        displayName: 'IBM Host File',
        iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
        brandColor: '#c4d5ff',
        description: 'The IBM Host File connector provides an API to work with off-line files of IBM origin.',
      },
      summary: 'Parse Host File Contents',
      description: 'Parse the contents of a file in IBM formats.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/releases/v1.0.1385/1.0.1385.2110/azurequeues/icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/hostfile',
      },
    },
  },
  {
    name: 'pollAvailable',
    id: 'pollAvailable',
    type: 'pollAvailable',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'When message is available in a queue',
      description: 'Triggers a flow when a message is available in a queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      operationKind: 'Polling',
      trigger: 'Single',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'pollMessages',
    id: 'pollMessages',
    type: 'pollMessages',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'When one or more messages are received from a queue (auto-complete)',
      description:
        'Triggers a flow when one or more messages are received from a queue using auto-complete. The received messages are deleted from the queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      operationKind: 'Polling',
      trigger: 'Batch',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'receiveMessage',
    id: 'receiveMessage',
    type: 'receiveMessage',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'Receive message',
      description: 'Returns a message from a queue using auto-complete. The received message is deleted from the queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'receiveBatch',
    id: 'receiveBatch',
    type: 'receiveBatch',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'Receive multiple messages',
      description:
        'Returns one or more messages from a queue using auto-complete. The received messages are deleted from the queue. If no maximum message count is provided, the default count is 20 messages.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'sendMessage',
    id: 'sendMessage',
    type: 'sendMessage',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'Send message',
      description: 'Sends a message to a queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'sendBatch',
    id: 'sendBatch',
    type: 'sendBatch',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'Send multiple messages',
      description: 'Sends one or more messages to a queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
    },
  },
  {
    name: 'moveMessageToDeadLetterQueue',
    id: 'moveMessageToDeadLetterQueue',
    type: 'moveMessageToDeadLetterQueue',
    properties: {
      api: {
        id: '/serviceProviders/mq',
        type: 'ServiceProvider',
        name: 'mq',
        displayName: 'MQ',
        iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
        brandColor: '#c4d5ff',
        description: 'The MQ connector provides an API to work with IBM MQ server.',
      },
      summary: 'Move message to MQ dead-letter queue',
      description: 'Move a selected message to the MQ dead-letter queue (DLQ)',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://cdnforlogicappsv2.blob.core.windows.net/connectoricons-edge-prod/IBM/MQ-icon.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/mq',
      },
    },
  },
  {
    name: 'receiveQueueMessages',
    id: 'receiveQueueMessages',
    type: 'receiveQueueMessages',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'When messages are available in a queue',
      description: 'This operation triggers a run when messages are available in a queue.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      trigger: 'Batch',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'receiveTopicMessages',
    id: 'receiveTopicMessages',
    type: 'receiveTopicMessages',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'When messages are available in a topic subscription',
      description: 'The operation triggers a run when a message is available in topic subscription.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      trigger: 'Batch',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'GetQueues',
    id: 'getQueues',
    type: 'GetQueues',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Get queues',
      description: 'Gets queues.',
      visibility: 'Internal',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
      },
    },
  },
  {
    name: 'GetTopics',
    id: 'getTopics',
    type: 'GetTopics',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Get topics',
      description: 'Gets topics.',
      visibility: 'Internal',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
      },
    },
  },
  {
    name: 'getTopicSubcriptions',
    id: 'getTopicSubcriptions',
    type: 'getTopicSubcriptions',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Get topic subscripions',
      description: 'Gets topic subscriptions.',
      visibility: 'Internal',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
      },
    },
  },
  {
    name: 'GetEntities',
    id: 'getEntities',
    type: 'GetEntities',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Get all queues and topics',
      description: 'Gets all queues and topics.',
      visibility: 'Internal',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
      annotation: {
        status: 'Preview',
      },
    },
  },
  {
    name: 'sendMessage',
    id: 'sendMessage',
    type: 'sendMessage',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Send message',
      description: 'Send message to a queue or topic.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'sendMessages',
    id: 'sendMessages',
    type: 'sendMessages',
    properties: {
      api: {
        id: '/serviceProviders/serviceBus',
        type: 'ServiceProvider',
        name: 'serviceBus',
        displayName: 'Service Bus',
        iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
        brandColor: '#c4d5ff',
        description: 'Connect to Azure Service Bus to send and receive messages.',
      },
      summary: 'Send multiple messages',
      description: 'This operation sends messages to a queue or topic.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/servicebus/icon_1.0.1274.1744.png',
    },
  },
  {
    name: 'whenFilesAreAddedOrModified',
    id: 'whenFilesAreAddedOrModified',
    type: 'whenFilesAreAddedOrModified',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'When a file is added or updated',
      description: 'This trigger fires when a new file is created or an existing file is updated in the watch folder.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      operationKind: 'Polling',
      trigger: 'Batch',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'getFileContent',
    id: 'getFileContent',
    type: 'getFileContent',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Get File Content',
      description:
        "This action fetches full file content given that the file size does not exceed maximum permissible limit of '209715200' bytes.",
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'uploadFileContent',
    id: 'uploadFileContent',
    type: 'uploadFileContent',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Upload File Content',
      description: 'Upload the provided content to a file with given file path.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'getMetadata',
    id: 'getMetadata',
    type: 'getMetadata',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Get file or directory metadata',
      description: 'Gets metadata of a file or a directory with the given path.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'listFolder',
    id: 'listFolder',
    type: 'listFolder',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'List Folder',
      description: 'List the files and folders present in the given folder with their metadata.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'deleteFile',
    id: 'deleteFile',
    type: 'deleteFile',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Delete File',
      description: 'Deletes the file with given file path.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'createFolder',
    id: 'createFolder',
    type: 'createFolder',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Create Folder',
      description: 'Create a new folder with given folder path.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'renameFile',
    id: 'renameFile',
    type: 'renameFile',
    properties: {
      api: {
        id: '/serviceProviders/Sftp',
        type: 'ServiceProvider',
        name: 'Sftp',
        displayName: 'SFTP',
        iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
        brandColor: '#e8bb00',
        description: 'Connect to a SFTP server to receive file updates.',
      },
      summary: 'Rename File',
      description: 'Change the name of the given file. The file will remain in the same directory.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#e8bb00',
      iconUri: 'https://connectoricons-prod.azureedge.net/sftpwithssh/icon_1.0.1355.2021.png',
      annotation: {
        status: 'Preview',
        family: '/serviceProviders/Sftp',
      },
    },
  },
  {
    name: 'executeQuery',
    id: 'executeQuery',
    type: 'executeQuery',
    properties: {
      api: {
        id: '/serviceProviders/sql',
        type: 'ServiceProvider',
        name: 'sql',
        displayName: 'SQL Server',
        iconUri: 'https://connectoricons-prod.azureedge.net/sql/icon_1.0.1339.1981.png',
        brandColor: '#c4d5ff',
        description: 'The SQL Server connector provides an API to work with SQL Databases.',
      },
      summary: 'Execute Query',
      description: 'Execute a SQL query.',
      visibility: 'Important',
      operationType: 'ServiceProvider',
      brandColor: '#c4d5ff',
      iconUri: 'https://connectoricons-prod.azureedge.net/sql/icon_1.0.1339.1981.png',
    },
  },
  {
    name: 'composeNew',
    id: 'composeNew',
    type: 'compose',
    properties: {
      api: {
        id: 'connectionProviders/dataOperationNew',
        name: 'dataOperationNew',
        displayName: 'Data Operations new',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/compose.svg',
        brandColor: '#8c6cff',
        description: 'Data Operations new',
      },
      summary: 'Compose',
      description: "Constructs an arbitrary object from the action's inputs.",
      visibility: 'Important',
      operationType: 'Compose',
      brandColor: '#8c6cff',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/compose.svg',
    },
  },
  {
    name: 'invokeWorkflow',
    id: 'invokeWorkflow',
    type: 'workflow',
    properties: {
      api: {
        id: 'connectionProviders/localWorkflowOperation',
        name: 'localWorkflowOperation',
        displayName: 'Workflow Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/workflow.svg',
        brandColor: '#59b2d9',
        description: 'Workflow Operations',
      },
      summary: 'Invoke a workflow in this workflow app',
      description: 'Invokes a workflow in this workflow app.',
      visibility: 'Important',
      operationType: 'Workflow',
      brandColor: '#59b2d9',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/workflow.svg',
    },
  },
  {
    name: 'xmlTransform',
    id: 'xmlTransform',
    type: 'xslt',
    properties: {
      api: {
        id: 'connectionProviders/xmlOperations',
        name: 'xmlOperations',
        displayName: 'XML Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/xml.svg',
        brandColor: '#804998',
        description: 'XML Operations',
      },
      summary: 'Transform XML',
      description: 'Transform XML using XSLT map.',
      visibility: 'Important',
      operationType: 'Xslt',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/xml.svg',
      annotation: {
        status: 'Preview',
        family: 'xmlOperations',
      },
    },
  },
  {
    name: 'xmlValidation',
    id: 'xmlValidation',
    type: 'XmlValidation',
    properties: {
      api: {
        id: 'connectionProviders/xmlOperations',
        name: 'xmlOperations',
        displayName: 'XML Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/xml.svg',
        brandColor: '#804998',
        description: 'XML Operations',
      },
      summary: 'XML Validation',
      description: 'Validate XML using schema.',
      visibility: 'Important',
      operationType: 'XmlValidation',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/xml.svg',
      annotation: {
        status: 'Preview',
        family: 'xmlOperations',
      },
    },
  },
  {
    name: 'liquidJsonToJson',
    id: 'liquidJsonToJson',
    type: 'Liquid',
    properties: {
      api: {
        id: 'connectionProviders/liquidOperations',
        name: 'liquidOperations',
        displayName: 'Liquid Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
        brandColor: '#804998',
        description: 'Liquid Operations',
      },
      summary: 'Transform JSON To JSON',
      description: 'Transform JSON to JSON using Liquid map.',
      visibility: 'Important',
      operationType: 'Liquid',
      operationKind: 'JsonToJson',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
      annotation: {
        status: 'Preview',
        family: 'liquidOperations',
      },
    },
  },
  {
    name: 'liquidJsonToText',
    id: 'liquidJsonToText',
    type: 'Liquid',
    properties: {
      api: {
        id: 'connectionProviders/liquidOperations',
        name: 'liquidOperations',
        displayName: 'Liquid Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
        brandColor: '#804998',
        description: 'Liquid Operations',
      },
      summary: 'Transform JSON To TEXT',
      description: 'Transform JSON to TEXT using Liquid map.',
      visibility: 'Important',
      operationType: 'Liquid',
      operationKind: 'JsonToText',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
      annotation: {
        status: 'Preview',
        family: 'liquidOperations',
      },
    },
  },
  {
    name: 'liquidXmlToJson',
    id: 'liquidXmlToJson',
    type: 'Liquid',
    properties: {
      api: {
        id: 'connectionProviders/liquidOperations',
        name: 'liquidOperations',
        displayName: 'Liquid Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
        brandColor: '#804998',
        description: 'Liquid Operations',
      },
      summary: 'Transform XML To JSON',
      description: 'Transform XML to JSON using Liquid map.',
      visibility: 'Important',
      operationType: 'Liquid',
      operationKind: 'XmlToJson',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
      annotation: {
        status: 'Preview',
        family: 'liquidOperations',
      },
    },
  },
  {
    name: 'liquidXmlToText',
    id: 'liquidXmlToText',
    type: 'Liquid',
    properties: {
      api: {
        id: 'connectionProviders/liquidOperations',
        name: 'liquidOperations',
        displayName: 'Liquid Operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
        brandColor: '#804998',
        description: 'Liquid Operations',
      },
      summary: 'Transform XML To TEXT',
      description: 'Transform XML to TEXT using Liquid map.',
      visibility: 'Important',
      operationType: 'Liquid',
      operationKind: 'XmlToText',
      brandColor: '#804998',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/liquid.svg',
      annotation: {
        status: 'Preview',
        family: 'liquidOperations',
      },
    },
  },
  {
    name: 'azureFunction',
    id: 'azureFunction',
    type: 'function',
    properties: {
      api: {
        id: '/connectionProviders/azureFunctionOperation',
        name: 'azureFunctionOperation',
        displayName: 'Azure Function operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/invokefunction.svg',
        brandColor: '#3999c6',
        description: 'Azure Function operations',
      },
      summary: 'Call an Azure function',
      description: 'Call an Azure function.',
      visibility: 'Important',
      operationType: 'Function',
      brandColor: '#3999c6',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/invokefunction.svg',
      // capabilities: ['azureConnection'], danielle
    },
  },
  {
    name: 'apiManagement',
    id: 'apiManagement',
    type: 'apiManagement',
    properties: {
      api: {
        id: '/connectionProviders/apiManagementOperation',
        name: 'apiManagementOperation',
        displayName: 'API Management operations',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/apimanagement.svg',
        brandColor: '#68217a',
        description: 'API Management operations',
      },
      summary: 'Call an Azure API Management API',
      description: 'Call an Azure API Management API.',
      visibility: 'Important',
      operationType: 'ApiManagement',
      brandColor: '#68217a',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/apimanagement.svg',
      // capabilities: ['azureConnection'],
    },
  },
  {
    name: 'javaScriptCode',
    id: 'javaScriptCode',
    type: 'javaScriptCode',
    properties: {
      api: {
        id: 'connectionProviders/inlineCode',
        name: 'inlineCode',
        displayName: 'Inline Code',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/inline_code.svg',
        brandColor: '#ba5d00',
        description: 'Inline Code',
      },
      summary: 'Execute JavaScript Code',
      description: 'Execute JavaScript Code',
      visibility: 'Important',
      operationType: 'JavaScriptCode',
      brandColor: '#ba5d00',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/javascript.svg',
    },
  },
  {
    name: 'flatFileDecoding',
    id: 'flatFileDecoding',
    type: 'flatFileDecoding',
    properties: {
      api: {
        id: 'connectionProviders/flatFileOperations',
        name: 'flatFileOperations',
        displayName: 'Flat File',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/flatfiledecoding.svg',
        brandColor: '#e68a00',
        description: 'Flat File',
      },
      summary: 'Flat File Decoding',
      description: 'Decodes incoming flat file.',
      visibility: 'Important',
      operationType: 'FlatFileDecoding',
      brandColor: '#e68a00',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/flatfiledecoding.svg',
      annotation: {
        status: 'Preview',
        family: 'flatFileOperations',
      },
    },
  },
  {
    name: 'flatFileEncoding',
    id: 'flatFileEncoding',
    type: 'flatFileEncoding',
    properties: {
      api: {
        id: 'connectionProviders/flatFileOperations',
        name: 'flatFileOperations',
        displayName: 'Flat File',
        iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/flatfiledecoding.svg',
        brandColor: '#e68a00',
        description: 'Flat File',
      },
      summary: 'Flat File Encoding',
      description: 'Encodes incoming XML file.',
      visibility: 'Important',
      operationType: 'FlatFileEncoding',
      brandColor: '#e68a00',
      iconUri: 'https://logicappsv2resources.blob.core.windows.net/icons/flatfileencoding.svg',
      annotation: {
        status: 'Preview',
        family: 'flatFileOperations',
      },
    },
  },
];
