import { defineConfig } from 'tsup';
import { lessLoader } from 'esbuild-plugin-less';

export default defineConfig({
  entry: ['src/index.ts'],
  treeshake: true,
  outDir: 'build/lib',
  sourcemap: true,
  minify: true,
  clean: true,
  // dts: true,
  splitting: true,
  tsconfig: 'tsconfig.json',
  format: ['esm'],
  external: [
    'react',
    'react-dom',
    '@microsoft/logic-apps-shared',
    '@fluentui/react',
    '@fluentui/react-components',
    '@fluentui/react-hooks',
    '@fluentui/react-icons',
    '@fluentui/theme',
    '@fluentui/utilities',
    '@xyflow/react',
    '@react-hookz/web',
    '@codemirror/autocomplete',
    '@codemirror/commands',
    '@codemirror/lang-javascript',
    '@codemirror/lang-json',
    '@codemirror/lang-python',
    '@codemirror/lang-xml',
    '@codemirror/lang-yaml',
    '@codemirror/language',
    '@codemirror/legacy-modes',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/html',
    '@lexical/link',
    '@lexical/list',
    '@lexical/react',
    '@lexical/rich-text',
    '@lexical/selection',
    '@lexical/table',
    '@lexical/utils',
    'dompurify',
    'fuse.js',
    'lexical',
    'prism-react-renderer',
    'react-dnd',
    'react-infinite-scroll-component',
    'react-intl',
    'react-markdown',
    'react-use',
    '@tanstack/react-query',
    '@tanstack/react-query-devtools',
    '@tanstack/react-query-persist-client',
    '@tanstack/query-sync-storage-persister',
  ],
  injectStyle: false,
  loader: {
    '.svg': 'dataurl',
  },
  esbuildPlugins: [lessLoader()],
});
