import type { ConnectionDictionary } from '../../models/Connection';

export const indexedConnections: ConnectionDictionary = {
  'target-/ns0:Root/Looping/Person/Name': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person/Name',
        name: 'Name',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Name',
        parentKey: '/ns0:Root/Looping/Person',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            fullName: 'Person',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Person/Name',
            name: 'Name',
            fullName: 'Name',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person/Name',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'TelephoneNumber',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                fullName: 'TelephoneNumber',
                repeating: false,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/Looping/Employee/TelephoneNumber',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee/TelephoneNumber': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee/TelephoneNumber',
        name: 'TelephoneNumber',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'TelephoneNumber',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            fullName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            fullName: 'TelephoneNumber',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee/TelephoneNumber',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/Looping/Person/Name',
          name: 'Name',
          schemaNodeDataType: 'String',
          normalizedDataType: 'String',
          properties: 'NotSpecified',
          fullName: 'Name',
          parentKey: '/ns0:Root/Looping/Person',
          nodeProperties: ['NotSpecified'],
          children: [],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping',
              name: 'Looping',
              fullName: 'Looping',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping/Person',
              name: 'Person',
              fullName: 'Person',
              repeating: true,
            },
            {
              key: '/ns0:Root/Looping/Person/Name',
              name: 'Name',
              fullName: 'Name',
              repeating: false,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/Looping/Person/Name',
      },
    ],
  },
  'target-/ns0:Root/Looping/Person': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person',
        name: 'Person',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/Looping/Person/Name',
            name: 'Name',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Name',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                fullName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Name',
                name: 'Name',
                fullName: 'Name',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Person/Address',
            name: 'Address',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Address',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                fullName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Address',
                name: 'Address',
                fullName: 'Address',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Person/Other',
            name: 'Other',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'Optional',
            fullName: 'Other',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: ['Optional'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                fullName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Other',
                name: 'Other',
                fullName: 'Other',
                repeating: false,
              },
            ],
          },
        ],
        fullName: 'Person',
        parentKey: '/ns0:Root/Looping',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            fullName: 'Person',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person',
    },
    inputs: {
      '0': [
        {
          node: {
            key: 'index',
            maxNumberOfInputs: 1,
            type: 'PseudoFunction',
            functionName: '',
            outputValueType: 'Any',
            inputs: [
              {
                name: 'Loop',
                allowedTypes: ['ComplexType'],
                isOptional: false,
                allowCustomInput: false,
                placeHolder: 'The source loop.',
              },
            ],
            displayName: 'Index',
            category: 'Collection',
            description: 'Adds an index value to the loop',
            children: [],
          },
          reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee',
        name: 'Employee',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'TelephoneNumber',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                fullName: 'TelephoneNumber',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Employee/Name',
            name: 'Name',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Name',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                fullName: 'Name',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Employee/Salary',
            name: 'Salary',
            schemaNodeDataType: 'Decimal',
            normalizedDataType: 'Decimal',
            properties: 'NotSpecified',
            fullName: 'Salary',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                fullName: 'Salary',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Employee/Country',
            name: 'Country',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Country',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                fullName: 'Country',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
            name: 'Dat_of_Birth',
            schemaNodeDataType: 'Date',
            normalizedDataType: 'DateTime',
            properties: 'NotSpecified',
            fullName: 'Dat_of_Birth',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                fullName: 'Dat_of_Birth',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/Employee/Address',
            name: 'Address',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Address',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                fullName: 'Address',
                repeating: false,
              },
            ],
          },
        ],
        fullName: 'Employee',
        parentKey: '/ns0:Root/Looping',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            fullName: 'Employee',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: 'index',
          maxNumberOfInputs: 1,
          type: 'PseudoFunction',
          functionName: '',
          outputValueType: 'Any',
          inputs: [
            {
              name: 'Loop',
              allowedTypes: ['ComplexType'],
              isOptional: false,
              allowCustomInput: false,
              placeHolder: 'The source loop.',
            },
          ],
          displayName: 'Index',
          category: 'Collection',
          description: 'Adds an index value to the loop',
          children: [],
        },
        reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
      },
    ],
  },
  'target-/ns0:Root/Looping/Person/Address': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person/Address',
        name: 'Address',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Address',
        parentKey: '/ns0:Root/Looping/Person',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            fullName: 'Person',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Person/Address',
            name: 'Address',
            fullName: 'Address',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person/Address',
    },
    inputs: {
      '0': [],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee/Name': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee/Name',
        name: 'Name',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Name',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            fullName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            fullName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Name',
            name: 'Name',
            fullName: 'Name',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee/Name',
    },
    inputs: {
      '0': [],
    },
    outputs: [],
  },
  'index-97A0763A-D86A-4018-B128-1DC23B3A461E': {
    self: {
      node: {
        key: 'index',
        maxNumberOfInputs: 1,
        type: 'PseudoFunction',
        functionName: '',
        outputValueType: 'Any',
        inputs: [
          {
            name: 'Loop',
            allowedTypes: ['ComplexType'],
            isOptional: false,
            allowCustomInput: false,
            placeHolder: 'The source loop.',
          },
        ],
        displayName: 'Index',
        category: 'Collection',
        description: 'Adds an index value to the loop',
        children: [],
      },
      reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'TelephoneNumber',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                    name: 'TelephoneNumber',
                    fullName: 'TelephoneNumber',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Name',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Name',
                    name: 'Name',
                    fullName: 'Name',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                schemaNodeDataType: 'Decimal',
                normalizedDataType: 'Decimal',
                properties: 'NotSpecified',
                fullName: 'Salary',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Salary',
                    name: 'Salary',
                    fullName: 'Salary',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Country',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Country',
                    name: 'Country',
                    fullName: 'Country',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                schemaNodeDataType: 'Date',
                normalizedDataType: 'DateTime',
                properties: 'NotSpecified',
                fullName: 'Dat_of_Birth',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                    name: 'Dat_of_Birth',
                    fullName: 'Dat_of_Birth',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Address',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    fullName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    fullName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Address',
                    name: 'Address',
                    fullName: 'Address',
                    repeating: false,
                  },
                ],
              },
            ],
            fullName: 'Employee',
            parentKey: '/ns0:Root/Looping',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                fullName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                fullName: 'Employee',
                repeating: true,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/Looping/Employee',
        },
      ],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/Looping/Person',
          name: 'Person',
          schemaNodeDataType: 'None',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/Looping/Person/Name',
              name: 'Name',
              schemaNodeDataType: 'String',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              fullName: 'Name',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: ['NotSpecified'],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  fullName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  fullName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Name',
                  name: 'Name',
                  fullName: 'Name',
                  repeating: false,
                },
              ],
            },
            {
              key: '/ns0:Root/Looping/Person/Address',
              name: 'Address',
              schemaNodeDataType: 'String',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              fullName: 'Address',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: ['NotSpecified'],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  fullName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  fullName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Address',
                  name: 'Address',
                  fullName: 'Address',
                  repeating: false,
                },
              ],
            },
            {
              key: '/ns0:Root/Looping/Person/Other',
              name: 'Other',
              schemaNodeDataType: 'String',
              normalizedDataType: 'String',
              properties: 'Optional',
              fullName: 'Other',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: ['Optional'],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  fullName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  fullName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Other',
                  name: 'Other',
                  fullName: 'Other',
                  repeating: false,
                },
              ],
            },
          ],
          fullName: 'Person',
          parentKey: '/ns0:Root/Looping',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping',
              name: 'Looping',
              fullName: 'Looping',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping/Person',
              name: 'Person',
              fullName: 'Person',
              repeating: true,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/Looping/Person',
      },
    ],
  },
} as ConnectionDictionary;
