import { FunctionCategory } from '../../models';
import type { ConnectionDictionary } from '../../models/Connection';
import { NormalizedDataType, SchemaNodeProperty } from '@microsoft/vscode-extension';

export const indexedConnections: ConnectionDictionary = {
  'target-/ns0:Root/Looping/Person/Name': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person/Name',
        name: 'Name',
        type: NormalizedDataType.String,
        properties: 'None',
        qName: 'Name',
        parentKey: '/ns0:Root/Looping/Person',
        nodeProperties: [SchemaNodeProperty.None],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            qName: 'Person',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Person/Name',
            name: 'Name',
            qName: 'Name',
            repeating: false,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person/Name',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'TelephoneNumber',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                qName: 'TelephoneNumber',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          reactFlowKey: 'source-/ns0:Root/Looping/Employee/TelephoneNumber',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee/TelephoneNumber': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee/TelephoneNumber',
        name: 'TelephoneNumber',
        type: NormalizedDataType.String,
        properties: 'None',
        qName: 'TelephoneNumber',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: [SchemaNodeProperty.None],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            qName: 'TelephoneNumber',
            repeating: false,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee/TelephoneNumber',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/Looping/Person/Name',
          name: 'Name',
          type: NormalizedDataType.String,
          properties: 'None',
          qName: 'Name',
          parentKey: '/ns0:Root/Looping/Person',
          nodeProperties: [SchemaNodeProperty.None],
          children: [],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              qName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping',
              name: 'Looping',
              qName: 'Looping',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping/Person',
              name: 'Person',
              qName: 'Person',
              repeating: true,
            },
            {
              key: '/ns0:Root/Looping/Person/Name',
              name: 'Name',
              qName: 'Name',
              repeating: false,
            },
          ],
          arrayItemIndex: undefined,
        },
        reactFlowKey: 'target-/ns0:Root/Looping/Person/Name',
      },
    ],
  },
  'target-/ns0:Root/Looping/Person': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person',
        name: 'Person',
        type: NormalizedDataType.Complex,
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/Looping/Person/Name',
            name: 'Name',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'Name',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                qName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Name',
                name: 'Name',
                qName: 'Name',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Person/Address',
            name: 'Address',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'Address',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                qName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Address',
                name: 'Address',
                qName: 'Address',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Person/Other',
            name: 'Other',
            type: NormalizedDataType.String,
            properties: 'Optional',
            qName: 'Other',
            parentKey: '/ns0:Root/Looping/Person',
            nodeProperties: [SchemaNodeProperty.Optional],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Person',
                name: 'Person',
                qName: 'Person',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Person/Other',
                name: 'Other',
                qName: 'Other',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
        ],
        qName: 'Person',
        parentKey: '/ns0:Root/Looping',
        nodeProperties: [SchemaNodeProperty.Repeating],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            qName: 'Person',
            repeating: true,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person',
    },
    inputs: {
      '0': [
        {
          node: {
            key: 'index',
            maxNumberOfInputs: 1,
            functionName: '',
            outputValueType: NormalizedDataType.Any,
            inputs: [
              {
                name: 'Loop',
                allowedTypes: [NormalizedDataType.Complex],
                isOptional: false,
                allowCustomInput: false,
                placeHolder: 'The source loop.',
              },
            ],
            displayName: 'Index',
            category: FunctionCategory.Collection,
            description: 'Adds an index value to the loop',
            children: [],
          },
          reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee',
        name: 'Employee',
        type: NormalizedDataType.Complex,
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'TelephoneNumber',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                qName: 'TelephoneNumber',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Employee/Name',
            name: 'Name',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'Name',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                qName: 'Name',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Employee/Salary',
            name: 'Salary',
            type: NormalizedDataType.Decimal,
            properties: 'None',
            qName: 'Salary',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                qName: 'Salary',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Employee/Country',
            name: 'Country',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'Country',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                qName: 'Country',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
            name: 'Dat_of_Birth',
            type: NormalizedDataType.DateTime,
            properties: 'None',
            qName: 'Dat_of_Birth',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                qName: 'Dat_of_Birth',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
          {
            key: '/ns0:Root/Looping/Employee/Address',
            name: 'Address',
            type: NormalizedDataType.String,
            properties: 'None',
            qName: 'Address',
            parentKey: '/ns0:Root/Looping/Employee',
            nodeProperties: [SchemaNodeProperty.None],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                qName: 'Address',
                repeating: false,
              },
            ],
            arrayItemIndex: undefined,
          },
        ],
        qName: 'Employee',
        parentKey: '/ns0:Root/Looping',
        nodeProperties: [SchemaNodeProperty.Repeating],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: 'index',
          maxNumberOfInputs: 1,
          functionName: '',
          outputValueType: NormalizedDataType.Any,
          inputs: [
            {
              name: 'Loop',
              allowedTypes: [NormalizedDataType.Complex],
              isOptional: false,
              allowCustomInput: false,
              placeHolder: 'The source loop.',
            },
          ],
          displayName: 'Index',
          category: FunctionCategory.Collection,
          description: 'Adds an index value to the loop',
          children: [],
        },
        reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
      },
    ],
  },
  'target-/ns0:Root/Looping/Person/Address': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Person/Address',
        name: 'Address',
        type: NormalizedDataType.String,
        properties: 'None',
        qName: 'Address',
        parentKey: '/ns0:Root/Looping/Person',
        nodeProperties: [SchemaNodeProperty.None],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Person',
            name: 'Person',
            qName: 'Person',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Person/Address',
            name: 'Address',
            qName: 'Address',
            repeating: false,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'target-/ns0:Root/Looping/Person/Address',
    },
    inputs: {
      '0': [],
    },
    outputs: [],
  },
  'source-/ns0:Root/Looping/Employee/Name': {
    self: {
      node: {
        key: '/ns0:Root/Looping/Employee/Name',
        name: 'Name',
        type: NormalizedDataType.String,
        properties: 'None',
        qName: 'Name',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: [SchemaNodeProperty.None],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Name',
            name: 'Name',
            qName: 'Name',
            repeating: false,
          },
        ],
        arrayItemIndex: undefined,
      },
      reactFlowKey: 'source-/ns0:Root/Looping/Employee/Name',
    },
    inputs: {
      '0': [],
    },
    outputs: [],
  },
  'index-97A0763A-D86A-4018-B128-1DC23B3A461E': {
    self: {
      node: {
        key: 'index',
        maxNumberOfInputs: 1,
        functionName: '',
        outputValueType: NormalizedDataType.Any,
        inputs: [
          {
            name: 'Loop',
            allowedTypes: [NormalizedDataType.Complex],
            isOptional: false,
            allowCustomInput: false,
            placeHolder: 'The source loop.',
          },
        ],
        displayName: 'Index',
        category: FunctionCategory.Collection,
        description: 'Adds an index value to the loop',
        children: [],
      },
      reactFlowKey: 'index-97A0763A-D86A-4018-B128-1DC23B3A461E',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            type: NormalizedDataType.Complex,
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                type: NormalizedDataType.String,
                properties: 'None',
                qName: 'TelephoneNumber',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                    name: 'TelephoneNumber',
                    qName: 'TelephoneNumber',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                type: NormalizedDataType.String,
                properties: 'None',
                qName: 'Name',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Name',
                    name: 'Name',
                    qName: 'Name',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                type: NormalizedDataType.Decimal,
                properties: 'None',
                qName: 'Salary',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Salary',
                    name: 'Salary',
                    qName: 'Salary',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                type: NormalizedDataType.String,
                properties: 'None',
                qName: 'Country',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Country',
                    name: 'Country',
                    qName: 'Country',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                type: NormalizedDataType.DateTime,
                properties: 'None',
                qName: 'Dat_of_Birth',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                    name: 'Dat_of_Birth',
                    qName: 'Dat_of_Birth',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                type: NormalizedDataType.String,
                properties: 'None',
                qName: 'Address',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: [SchemaNodeProperty.None],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Address',
                    name: 'Address',
                    qName: 'Address',
                    repeating: false,
                  },
                ],
                arrayItemIndex: undefined,
              },
            ],
            qName: 'Employee',
            parentKey: '/ns0:Root/Looping',
            nodeProperties: [SchemaNodeProperty.Repeating],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
            ],
            arrayItemIndex: undefined,
          },
          reactFlowKey: 'source-/ns0:Root/Looping/Employee',
        },
      ],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/Looping/Person',
          name: 'Person',
          type: NormalizedDataType.Complex,
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/Looping/Person/Name',
              name: 'Name',
              type: NormalizedDataType.String,
              properties: 'None',
              qName: 'Name',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: [SchemaNodeProperty.None],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  qName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  qName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  qName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Name',
                  name: 'Name',
                  qName: 'Name',
                  repeating: false,
                },
              ],
              arrayItemIndex: undefined,
            },
            {
              key: '/ns0:Root/Looping/Person/Address',
              name: 'Address',
              type: NormalizedDataType.String,
              properties: 'None',
              qName: 'Address',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: [SchemaNodeProperty.None],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  qName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  qName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  qName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Address',
                  name: 'Address',
                  qName: 'Address',
                  repeating: false,
                },
              ],
              arrayItemIndex: undefined,
            },
            {
              key: '/ns0:Root/Looping/Person/Other',
              name: 'Other',
              type: NormalizedDataType.String,
              properties: 'Optional',
              qName: 'Other',
              parentKey: '/ns0:Root/Looping/Person',
              nodeProperties: [SchemaNodeProperty.Optional],
              children: [],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  qName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping',
                  name: 'Looping',
                  qName: 'Looping',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/Looping/Person',
                  name: 'Person',
                  qName: 'Person',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/Looping/Person/Other',
                  name: 'Other',
                  qName: 'Other',
                  repeating: false,
                },
              ],
              arrayItemIndex: undefined,
            },
          ],
          qName: 'Person',
          parentKey: '/ns0:Root/Looping',
          nodeProperties: [SchemaNodeProperty.Repeating],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              qName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping',
              name: 'Looping',
              qName: 'Looping',
              repeating: false,
            },
            {
              key: '/ns0:Root/Looping/Person',
              name: 'Person',
              qName: 'Person',
              repeating: true,
            },
          ],
          arrayItemIndex: undefined,
        },
        reactFlowKey: 'target-/ns0:Root/Looping/Person',
      },
    ],
  },
};
