import { NormalizedDataType, SchemaNodeProperty } from '../../models';
import type { Connection, ConnectionDictionary } from '../../models/Connection';

export const manyToManyConnectionSourceName = 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate';
export const manyToManyConnectionTargetName = 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date';

export const manyToOneConnectionSourceName = 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate';
export const manyToOneConnectionTargetName = 'target-/ns0:Root/ManyToOne/Date/DayName';

export const manyToManyConnectionFromSource: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
      name: 'SourceDate',
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      fullName: 'SourceDate',
      parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      children: [],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany',
          name: 'ManyToMany',
          fullName: 'ManyToMany',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear',
          name: 'SourceYear',
          fullName: 'SourceYear',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
          name: 'SourceMonth',
          fullName: 'SourceMonth',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
          name: 'SourceDay',
          fullName: 'SourceDay',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
          name: 'SourceDate',
          fullName: 'SourceDate',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'target-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
  },
  inputs: {
    '0': [
      {
        node: {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
          name: 'SourceDate',
          normalizedDataType: NormalizedDataType.String,
          properties: 'NotSpecified',
          fullName: 'SourceDate',
          parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
          nodeProperties: [SchemaNodeProperty.NotSpecified],
          children: [],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToMany',
              name: 'ManyToMany',
              fullName: 'ManyToMany',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToMany/SourceYear',
              name: 'SourceYear',
              fullName: 'SourceYear',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
              name: 'SourceMonth',
              fullName: 'SourceMonth',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
              name: 'SourceDay',
              fullName: 'SourceDay',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
              name: 'SourceDate',
              fullName: 'SourceDate',
              repeating: false,
            },
          ],
        },
        reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
      },
    ],
  },
  outputs: [],
};

export const manyToManyConnectionFromTarget: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
      name: 'SourceDate',
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      fullName: 'SourceDate',
      parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      children: [],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany',
          name: 'ManyToMany',
          fullName: 'ManyToMany',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear',
          name: 'SourceYear',
          fullName: 'SourceYear',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
          name: 'SourceMonth',
          fullName: 'SourceMonth',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
          name: 'SourceDay',
          fullName: 'SourceDay',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
          name: 'SourceDate',
          fullName: 'SourceDate',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
  },
  inputs: {
    '0': [],
  },
  outputs: [
    {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
        name: 'Date',
        normalizedDataType: NormalizedDataType.String,
        properties: 'NotSpecified',
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
        nodeProperties: [SchemaNodeProperty.NotSpecified],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToMany',
            name: 'ManyToMany',
            fullName: 'ManyToMany',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToMany/Year',
            name: 'Year',
            fullName: 'Year',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            fullName: 'Month',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            fullName: 'Day',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            fullName: 'Date',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
    },
  ],
};

export const manyToOneConnectionFromTarget: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToOne/Date/DayName',
      name: 'DayName',
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      children: [],
      fullName: 'DayName',
      parentKey: '/ns0:Root/ManyToOne/Date',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToOne',
          name: 'ManyToOne',
          fullName: 'ManyToOne',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToOne/Date',
          name: 'Date',
          fullName: 'Date',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToOne/Date/DayName',
          name: 'DayName',
          fullName: 'DayName',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'target-/ns0:Root/ManyToOne/Date/DayName',
  },
  inputs: {
    '0': [
      {
        node: {
          key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
          name: 'SourceDate',
          normalizedDataType: NormalizedDataType.String,
          properties: 'NotSpecified',
          fullName: 'SourceDate',
          parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
          nodeProperties: [SchemaNodeProperty.NotSpecified],
          children: [],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne',
              name: 'ManyToOne',
              fullName: 'ManyToOne',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne/SourceYear',
              name: 'SourceYear',
              fullName: 'SourceYear',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
              name: 'SourceMonth',
              fullName: 'SourceMonth',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
              name: 'SourceDay',
              fullName: 'SourceDay',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
              name: 'SourceDate',
              fullName: 'SourceDate',
              repeating: false,
            },
          ],
        },
        reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
      },
    ],
  },
  outputs: [],
};

export const manyToOneConnectionFromSource: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
      name: 'SourceDate',
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      fullName: 'SourceDate',
      parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      children: [],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToOne',
          name: 'ManyToOne',
          fullName: 'ManyToOne',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToOne/SourceYear',
          name: 'SourceYear',
          fullName: 'SourceYear',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
          name: 'SourceMonth',
          fullName: 'SourceMonth',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
          name: 'SourceDay',
          fullName: 'SourceDay',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
          name: 'SourceDate',
          fullName: 'SourceDate',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
  },
  inputs: {
    '0': [],
  },
  outputs: [
    {
      node: {
        key: '/ns0:Root/ManyToOne/Date/DayName',
        name: 'DayName',
        normalizedDataType: NormalizedDataType.String,
        properties: 'NotSpecified',
        children: [],
        fullName: 'DayName',
        parentKey: '/ns0:Root/ManyToOne/Date',
        nodeProperties: [SchemaNodeProperty.NotSpecified],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/Date',
            name: 'Date',
            fullName: 'Date',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/Date/DayName',
            name: 'DayName',
            fullName: 'DayName',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToOne/Date/DayName',
    },
  ],
};

export const fullMapForSimplifiedLoop: ConnectionDictionary = {
  // WARNING loss of type safety here because of enums
  'target-/ns0:Root/ManyToMany/Year/Month/Day/Date': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
        name: 'Date',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'Date',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Date',
            parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
        name: 'SourceDate',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'SourceDate',
        parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
          { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
          { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay', name: 'SourceDay', fullName: 'SourceDay', repeating: true },
          {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'SourceDate',
            fullName: 'SourceDate',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
          name: 'Date',
          normalizedDataType: 'String',
          properties: 'NotSpecified',
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
          nodeProperties: ['NotSpecified'],
          children: [],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year/Month/Day': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day',
        name: 'Day',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Date',
            parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
            ],
          },
        ],
        fullName: 'Day',
        parentKey: '/ns0:Root/ManyToMany/Year/Month',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'SourceDate',
                parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                  { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    fullName: 'SourceDate',
                    repeating: false,
                  },
                ],
              },
            ],
            fullName: 'SourceDay',
            parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay', name: 'SourceDay', fullName: 'SourceDay', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
        name: 'SourceDay',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'SourceDate',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'SourceDate',
            parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay', name: 'SourceDay', fullName: 'SourceDay', repeating: true },
              {
                key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                fullName: 'SourceDate',
                repeating: false,
              },
            ],
          },
        ],
        fullName: 'SourceDay',
        parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
          { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
          { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay', name: 'SourceDay', fullName: 'SourceDay', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month/Day',
          name: 'Day',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
              name: 'Date',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              fullName: 'Date',
              parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
              nodeProperties: ['NotSpecified'],
              children: [],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
              ],
            },
          ],
          fullName: 'Day',
          parentKey: '/ns0:Root/ManyToMany/Year/Month',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year/Month': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month',
        name: 'Month',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                name: 'Date',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Date',
                parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                ],
              },
            ],
            fullName: 'Day',
            parentKey: '/ns0:Root/ManyToMany/Year/Month',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            ],
          },
        ],
        fullName: 'Month',
        parentKey: '/ns0:Root/ManyToMany/Year',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day',
                name: 'Day',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                    name: 'Date',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'Date',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                    ],
                  },
                ],
                fullName: 'Day',
                parentKey: '/ns0:Root/ManyToMany/Year/Month',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                ],
              },
            ],
            fullName: 'Month',
            parentKey: '/ns0:Root/ManyToMany/Year',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
        name: 'SourceMonth',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'SourceDate',
                parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                  { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    fullName: 'SourceDate',
                    repeating: false,
                  },
                ],
              },
            ],
            fullName: 'SourceDay',
            parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay', name: 'SourceDay', fullName: 'SourceDay', repeating: true },
            ],
          },
        ],
        fullName: 'SourceMonth',
        parentKey: '/ns0:Root/ManyToMany/SourceYear',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
          { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear/SourceMonth',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month',
          name: 'Month',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day',
              name: 'Day',
              normalizedDataType: 'ComplexType',
              properties: 'Repeating',
              children: [
                {
                  key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                  name: 'Date',
                  normalizedDataType: 'String',
                  properties: 'NotSpecified',
                  fullName: 'Date',
                  parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                  nodeProperties: ['NotSpecified'],
                  children: [],
                  pathToRoot: [
                    { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                    { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                    { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                  ],
                },
              ],
              fullName: 'Day',
              parentKey: '/ns0:Root/ManyToMany/Year/Month',
              nodeProperties: ['Repeating'],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              ],
            },
          ],
          fullName: 'Month',
          parentKey: '/ns0:Root/ManyToMany/Year',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year',
        name: 'Year',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day',
                name: 'Day',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                    name: 'Date',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'Date',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                    ],
                  },
                ],
                fullName: 'Day',
                parentKey: '/ns0:Root/ManyToMany/Year/Month',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                ],
              },
            ],
            fullName: 'Month',
            parentKey: '/ns0:Root/ManyToMany/Year',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            ],
          },
        ],
        fullName: 'Year',
        parentKey: '/ns0:Root/ManyToMany',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/SourceYear',
            name: 'SourceYear',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
                name: 'SourceMonth',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    normalizedDataType: 'ComplexType',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                        name: 'SourceDate',
                        normalizedDataType: 'String',
                        properties: 'NotSpecified',
                        fullName: 'SourceDate',
                        parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                        nodeProperties: ['NotSpecified'],
                        children: [],
                        pathToRoot: [
                          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                          { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                          {
                            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
                            name: 'SourceMonth',
                            fullName: 'SourceMonth',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                            name: 'SourceDay',
                            fullName: 'SourceDay',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                            name: 'SourceDate',
                            fullName: 'SourceDate',
                            repeating: false,
                          },
                        ],
                      },
                    ],
                    fullName: 'SourceDay',
                    parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
                    nodeProperties: ['Repeating'],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                      { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                      {
                        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                        name: 'SourceDay',
                        fullName: 'SourceDay',
                        repeating: true,
                      },
                    ],
                  },
                ],
                fullName: 'SourceMonth',
                parentKey: '/ns0:Root/ManyToMany/SourceYear',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                  { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                ],
              },
            ],
            fullName: 'SourceYear',
            parentKey: '/ns0:Root/ManyToMany',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/SourceYear': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/SourceYear',
        name: 'SourceYear',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
            name: 'SourceMonth',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'SourceDate',
                    parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                      { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                      {
                        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                        name: 'SourceDay',
                        fullName: 'SourceDay',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay/SourceDate',
                        name: 'SourceDate',
                        fullName: 'SourceDate',
                        repeating: false,
                      },
                    ],
                  },
                ],
                fullName: 'SourceDay',
                parentKey: '/ns0:Root/ManyToMany/SourceYear/SourceMonth',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
                  { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
                  {
                    key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                ],
              },
            ],
            fullName: 'SourceMonth',
            parentKey: '/ns0:Root/ManyToMany/SourceYear',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
              { key: '/ns0:Root/ManyToMany/SourceYear/SourceMonth', name: 'SourceMonth', fullName: 'SourceMonth', repeating: true },
            ],
          },
        ],
        fullName: 'SourceYear',
        parentKey: '/ns0:Root/ManyToMany',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/SourceYear', name: 'SourceYear', fullName: 'SourceYear', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/SourceYear',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year',
          name: 'Year',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month',
              name: 'Month',
              normalizedDataType: 'ComplexType',
              properties: 'Repeating',
              children: [
                {
                  key: '/ns0:Root/ManyToMany/Year/Month/Day',
                  name: 'Day',
                  normalizedDataType: 'ComplexType',
                  properties: 'Repeating',
                  children: [
                    {
                      key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                      name: 'Date',
                      normalizedDataType: 'String',
                      properties: 'NotSpecified',
                      fullName: 'Date',
                      parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                      nodeProperties: ['NotSpecified'],
                      children: [],
                      pathToRoot: [
                        { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                        { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                        { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                      ],
                    },
                  ],
                  fullName: 'Day',
                  parentKey: '/ns0:Root/ManyToMany/Year/Month',
                  nodeProperties: ['Repeating'],
                  pathToRoot: [
                    { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                    { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                    { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  ],
                },
              ],
              fullName: 'Month',
              parentKey: '/ns0:Root/ManyToMany/Year',
              nodeProperties: ['Repeating'],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              ],
            },
          ],
          fullName: 'Year',
          parentKey: '/ns0:Root/ManyToMany',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year',
      },
    ],
  },
} as ConnectionDictionary;

export const fullConnectionDictionaryForOneToManyLoop: ConnectionDictionary = {
  'target-/ns0:Root/ManyToOne/Date/DayName': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/Date/DayName',
        name: 'DayName',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        children: [],
        fullName: 'DayName',
        parentKey: '/ns0:Root/ManyToOne/Date',
        nodeProperties: ['NotSpecified'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/Date',
            name: 'Date',
            fullName: 'Date',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/Date/DayName',
            name: 'DayName',
            fullName: 'DayName',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToOne/Date/DayName',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'SourceDate',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'SourceDate',
            parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                fullName: 'SourceDay',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                fullName: 'SourceDate',
                repeating: false,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
        name: 'SourceDate',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'SourceDate',
        parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear',
            name: 'SourceYear',
            fullName: 'SourceYear',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            name: 'SourceMonth',
            fullName: 'SourceMonth',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            fullName: 'SourceDay',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'SourceDate',
            fullName: 'SourceDate',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToOne/Date/DayName',
          name: 'DayName',
          normalizedDataType: 'String',
          properties: 'NotSpecified',
          children: [],
          fullName: 'DayName',
          parentKey: '/ns0:Root/ManyToOne/Date',
          nodeProperties: ['NotSpecified'],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne',
              name: 'ManyToOne',
              fullName: 'ManyToOne',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne/Date',
              name: 'Date',
              fullName: 'Date',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToOne/Date/DayName',
              name: 'DayName',
              fullName: 'DayName',
              repeating: false,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToOne/Date/DayName',
      },
    ],
  },
  'target-/ns0:Root/ManyToOne/Date': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/Date',
        name: 'Date',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToOne/Date/DayName',
            name: 'DayName',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            children: [],
            fullName: 'DayName',
            parentKey: '/ns0:Root/ManyToOne/Date',
            nodeProperties: ['NotSpecified'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/Date',
                name: 'Date',
                fullName: 'Date',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/Date/DayName',
                name: 'DayName',
                fullName: 'DayName',
                repeating: false,
              },
            ],
          },
        ],
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToOne',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/Date',
            name: 'Date',
            fullName: 'Date',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToOne/Date',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'SourceDate',
                parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne',
                    name: 'ManyToOne',
                    fullName: 'ManyToOne',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear',
                    name: 'SourceYear',
                    fullName: 'SourceYear',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    name: 'SourceMonth',
                    fullName: 'SourceMonth',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    fullName: 'SourceDate',
                    repeating: false,
                  },
                ],
              },
            ],
            fullName: 'SourceDay',
            parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                fullName: 'SourceDay',
                repeating: true,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
        },
        {
          node: {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            name: 'SourceMonth',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'SourceDate',
                    parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        fullName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne',
                        name: 'ManyToOne',
                        fullName: 'ManyToOne',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear',
                        name: 'SourceYear',
                        fullName: 'SourceYear',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                        name: 'SourceMonth',
                        fullName: 'SourceMonth',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                        name: 'SourceDay',
                        fullName: 'SourceDay',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                        name: 'SourceDate',
                        fullName: 'SourceDate',
                        repeating: false,
                      },
                    ],
                  },
                ],
                fullName: 'SourceDay',
                parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne',
                    name: 'ManyToOne',
                    fullName: 'ManyToOne',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear',
                    name: 'SourceYear',
                    fullName: 'SourceYear',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    name: 'SourceMonth',
                    fullName: 'SourceMonth',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                ],
              },
            ],
            fullName: 'SourceMonth',
            parentKey: '/ns0:Root/ManyToOne/SourceYear',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth',
        },
        {
          node: {
            key: '/ns0:Root/ManyToOne/SourceYear',
            name: 'SourceYear',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    normalizedDataType: 'ComplexType',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                        name: 'SourceDate',
                        normalizedDataType: 'String',
                        properties: 'NotSpecified',
                        fullName: 'SourceDate',
                        parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                        nodeProperties: ['NotSpecified'],
                        children: [],
                        pathToRoot: [
                          {
                            key: '/ns0:Root',
                            name: 'Root',
                            fullName: 'ns0:Root',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/ManyToOne',
                            name: 'ManyToOne',
                            fullName: 'ManyToOne',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/ManyToOne/SourceYear',
                            name: 'SourceYear',
                            fullName: 'SourceYear',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                            name: 'SourceMonth',
                            fullName: 'SourceMonth',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                            name: 'SourceDay',
                            fullName: 'SourceDay',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                            name: 'SourceDate',
                            fullName: 'SourceDate',
                            repeating: false,
                          },
                        ],
                      },
                    ],
                    fullName: 'SourceDay',
                    parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    nodeProperties: ['Repeating'],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        fullName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne',
                        name: 'ManyToOne',
                        fullName: 'ManyToOne',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear',
                        name: 'SourceYear',
                        fullName: 'SourceYear',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                        name: 'SourceMonth',
                        fullName: 'SourceMonth',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                        name: 'SourceDay',
                        fullName: 'SourceDay',
                        repeating: true,
                      },
                    ],
                  },
                ],
                fullName: 'SourceMonth',
                parentKey: '/ns0:Root/ManyToOne/SourceYear',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne',
                    name: 'ManyToOne',
                    fullName: 'ManyToOne',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear',
                    name: 'SourceYear',
                    fullName: 'SourceYear',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    name: 'SourceMonth',
                    fullName: 'SourceMonth',
                    repeating: true,
                  },
                ],
              },
            ],
            fullName: 'SourceYear',
            parentKey: '/ns0:Root/ManyToOne',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
        name: 'SourceDay',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
            name: 'SourceDate',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'SourceDate',
            parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                fullName: 'SourceDay',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                name: 'SourceDate',
                fullName: 'SourceDate',
                repeating: false,
              },
            ],
          },
        ],
        fullName: 'SourceDay',
        parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear',
            name: 'SourceYear',
            fullName: 'SourceYear',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            name: 'SourceMonth',
            fullName: 'SourceMonth',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            fullName: 'SourceDay',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToOne/Date',
          name: 'Date',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToOne/Date/DayName',
              name: 'DayName',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              children: [],
              fullName: 'DayName',
              parentKey: '/ns0:Root/ManyToOne/Date',
              nodeProperties: ['NotSpecified'],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne',
                  name: 'ManyToOne',
                  fullName: 'ManyToOne',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date',
                  name: 'Date',
                  fullName: 'Date',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date/DayName',
                  name: 'DayName',
                  fullName: 'DayName',
                  repeating: false,
                },
              ],
            },
          ],
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToOne',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne',
              name: 'ManyToOne',
              fullName: 'ManyToOne',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne/Date',
              name: 'Date',
              fullName: 'Date',
              repeating: true,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToOne/Date',
      },
    ],
  },
  'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
        name: 'SourceMonth',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
            name: 'SourceDay',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceSourceDate',
                name: 'SourceSourceDate',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'SourceSourceDate',
                parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne',
                    name: 'ManyToOne',
                    fullName: 'ManyToOne',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear',
                    name: 'SourceYear',
                    fullName: 'SourceYear',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    name: 'SourceMonth',
                    fullName: 'SourceMonth',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceSourceDate',
                    name: 'SourceSourceDate',
                    fullName: 'SourceSourceDate',
                    repeating: false,
                  },
                ],
              },
            ],
            fullName: 'SourceDay',
            parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                fullName: 'SourceDay',
                repeating: true,
              },
            ],
          },
        ],
        fullName: 'SourceMonth',
        parentKey: '/ns0:Root/ManyToOne/SourceYear',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear',
            name: 'SourceYear',
            fullName: 'SourceYear',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            name: 'SourceMonth',
            fullName: 'SourceMonth',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear/SourceMonth',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToOne/Date',
          name: 'Date',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToOne/Date/DayName',
              name: 'DayName',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              children: [],
              fullName: 'DayName',
              parentKey: '/ns0:Root/ManyToOne/Date',
              nodeProperties: ['NotSpecified'],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne',
                  name: 'ManyToOne',
                  fullName: 'ManyToOne',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date',
                  name: 'Date',
                  fullName: 'Date',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date/DayName',
                  name: 'DayName',
                  fullName: 'DayName',
                  repeating: false,
                },
              ],
            },
          ],
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToOne',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne',
              name: 'ManyToOne',
              fullName: 'ManyToOne',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne/Date',
              name: 'Date',
              fullName: 'Date',
              repeating: true,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToOne/Date',
      },
    ],
  },
  'source-/ns0:Root/ManyToOne/SourceYear': {
    self: {
      node: {
        key: '/ns0:Root/ManyToOne/SourceYear',
        name: 'SourceYear',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
            name: 'SourceMonth',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                name: 'SourceDay',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                    name: 'SourceDate',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'SourceDate',
                    parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        fullName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne',
                        name: 'ManyToOne',
                        fullName: 'ManyToOne',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear',
                        name: 'SourceYear',
                        fullName: 'SourceYear',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                        name: 'SourceMonth',
                        fullName: 'SourceMonth',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                        name: 'SourceDay',
                        fullName: 'SourceDay',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay/SourceDate',
                        name: 'SourceDate',
                        fullName: 'SourceDate',
                        repeating: false,
                      },
                    ],
                  },
                ],
                fullName: 'SourceDay',
                parentKey: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    fullName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne',
                    name: 'ManyToOne',
                    fullName: 'ManyToOne',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear',
                    name: 'SourceYear',
                    fullName: 'SourceYear',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                    name: 'SourceMonth',
                    fullName: 'SourceMonth',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth/SourceDay',
                    name: 'SourceDay',
                    fullName: 'SourceDay',
                    repeating: true,
                  },
                ],
              },
            ],
            fullName: 'SourceMonth',
            parentKey: '/ns0:Root/ManyToOne/SourceYear',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                fullName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne',
                name: 'ManyToOne',
                fullName: 'ManyToOne',
                repeating: false,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear',
                name: 'SourceYear',
                fullName: 'SourceYear',
                repeating: true,
              },
              {
                key: '/ns0:Root/ManyToOne/SourceYear/SourceMonth',
                name: 'SourceMonth',
                fullName: 'SourceMonth',
                repeating: true,
              },
            ],
          },
        ],
        fullName: 'SourceYear',
        parentKey: '/ns0:Root/ManyToOne',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne',
            name: 'ManyToOne',
            fullName: 'ManyToOne',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToOne/SourceYear',
            name: 'SourceYear',
            fullName: 'SourceYear',
            repeating: true,
          },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToOne/SourceYear',
    },
    inputs: {
      '0': [],
    },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToOne/Date',
          name: 'Date',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToOne/Date/DayName',
              name: 'DayName',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              children: [],
              fullName: 'DayName',
              parentKey: '/ns0:Root/ManyToOne/Date',
              nodeProperties: ['NotSpecified'],
              pathToRoot: [
                {
                  key: '/ns0:Root',
                  name: 'Root',
                  fullName: 'ns0:Root',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne',
                  name: 'ManyToOne',
                  fullName: 'ManyToOne',
                  repeating: false,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date',
                  name: 'Date',
                  fullName: 'Date',
                  repeating: true,
                },
                {
                  key: '/ns0:Root/ManyToOne/Date/DayName',
                  name: 'DayName',
                  fullName: 'DayName',
                  repeating: false,
                },
              ],
            },
          ],
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToOne',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne',
              name: 'ManyToOne',
              fullName: 'ManyToOne',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToOne/Date',
              name: 'Date',
              fullName: 'Date',
              repeating: true,
            },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToOne/Date',
      },
    ],
  },
} as ConnectionDictionary;
