import { NormalizedDataType, SchemaNodeDataType, SchemaNodeProperty } from '../../models';
import type { Connection, ConnectionDictionary } from '../../models/Connection';

export const connection1Id = 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date';
export const connection2Id = 'source-/ns0:Root/ManyToMany/Year/Month/Day/Date';

export const connection1: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
      name: 'Date',
      schemaNodeDataType: SchemaNodeDataType.String,
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      fullName: 'Date',
      parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      children: [],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany',
          name: 'ManyToMany',
          fullName: 'ManyToMany',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany/Year',
          name: 'Year',
          fullName: 'Year',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month',
          name: 'Month',
          fullName: 'Month',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month/Day',
          name: 'Day',
          fullName: 'Day',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
          name: 'Date',
          fullName: 'Date',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
  },
  inputs: {
    '0': [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
          name: 'Date',
          schemaNodeDataType: SchemaNodeDataType.String,
          normalizedDataType: NormalizedDataType.String,
          properties: 'NotSpecified',
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
          nodeProperties: [SchemaNodeProperty.NotSpecified],
          children: [],
          pathToRoot: [
            {
              key: '/ns0:Root',
              name: 'Root',
              fullName: 'ns0:Root',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToMany',
              name: 'ManyToMany',
              fullName: 'ManyToMany',
              repeating: false,
            },
            {
              key: '/ns0:Root/ManyToMany/Year',
              name: 'Year',
              fullName: 'Year',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/Year/Month',
              name: 'Month',
              fullName: 'Month',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day',
              name: 'Day',
              fullName: 'Day',
              repeating: true,
            },
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
              name: 'Date',
              fullName: 'Date',
              repeating: false,
            },
          ],
        },
        reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day/Date',
      },
    ],
  },
  outputs: [],
};

export const connection2: Connection = {
  self: {
    node: {
      key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
      name: 'Date',
      schemaNodeDataType: SchemaNodeDataType.String,
      normalizedDataType: NormalizedDataType.String,
      properties: 'NotSpecified',
      fullName: 'Date',
      parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
      nodeProperties: [SchemaNodeProperty.NotSpecified],
      children: [],
      pathToRoot: [
        {
          key: '/ns0:Root',
          name: 'Root',
          fullName: 'ns0:Root',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany',
          name: 'ManyToMany',
          fullName: 'ManyToMany',
          repeating: false,
        },
        {
          key: '/ns0:Root/ManyToMany/Year',
          name: 'Year',
          fullName: 'Year',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month',
          name: 'Month',
          fullName: 'Month',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month/Day',
          name: 'Day',
          fullName: 'Day',
          repeating: true,
        },
        {
          key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
          name: 'Date',
          fullName: 'Date',
          repeating: false,
        },
      ],
    },
    reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day/Date',
  },
  inputs: {
    '0': [],
  },
  outputs: [
    {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
        name: 'Date',
        schemaNodeDataType: SchemaNodeDataType.String,
        normalizedDataType: NormalizedDataType.String,
        properties: 'NotSpecified',
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
        nodeProperties: [SchemaNodeProperty.NotSpecified],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            fullName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToMany',
            name: 'ManyToMany',
            fullName: 'ManyToMany',
            repeating: false,
          },
          {
            key: '/ns0:Root/ManyToMany/Year',
            name: 'Year',
            fullName: 'Year',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            fullName: 'Month',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            fullName: 'Day',
            repeating: true,
          },
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            fullName: 'Date',
            repeating: false,
          },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
    },
  ],
};

export const fullMapForSimplifiedLoop: ConnectionDictionary = {
  // WARNING loss of type safety here because of enums
  'target-/ns0:Root/ManyToMany/Year/Month/Day/Date': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
        name: 'Date',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Date',
            parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day/Date',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/Year/Month/Day/Date': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
        name: 'Date',
        schemaNodeDataType: 'String',
        normalizedDataType: 'String',
        properties: 'NotSpecified',
        fullName: 'Date',
        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
        nodeProperties: ['NotSpecified'],
        children: [],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day/Date',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
          name: 'Date',
          schemaNodeDataType: 'String',
          normalizedDataType: 'String',
          properties: 'NotSpecified',
          fullName: 'Date',
          parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
          nodeProperties: ['NotSpecified'],
          children: [],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day/Date',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year/Month/Day': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day',
        name: 'Day',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Date',
            parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
            ],
          },
        ],
        fullName: 'Day',
        parentKey: '/ns0:Root/ManyToMany/Year/Month',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                name: 'Date',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Date',
                parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                ],
              },
            ],
            fullName: 'Day',
            parentKey: '/ns0:Root/ManyToMany/Year/Month',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/Year/Month/Day': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month/Day',
        name: 'Day',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
            name: 'Date',
            schemaNodeDataType: 'String',
            normalizedDataType: 'String',
            properties: 'NotSpecified',
            fullName: 'Date',
            parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
            nodeProperties: ['NotSpecified'],
            children: [],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
            ],
          },
        ],
        fullName: 'Day',
        parentKey: '/ns0:Root/ManyToMany/Year/Month',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month/Day',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month/Day',
          name: 'Day',
          schemaNodeDataType: 'None',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
              name: 'Date',
              schemaNodeDataType: 'String',
              normalizedDataType: 'String',
              properties: 'NotSpecified',
              fullName: 'Date',
              parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
              nodeProperties: ['NotSpecified'],
              children: [],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
              ],
            },
          ],
          fullName: 'Day',
          parentKey: '/ns0:Root/ManyToMany/Year/Month',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month/Day',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year/Month': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month',
        name: 'Month',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                name: 'Date',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Date',
                parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                ],
              },
            ],
            fullName: 'Day',
            parentKey: '/ns0:Root/ManyToMany/Year/Month',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            ],
          },
        ],
        fullName: 'Month',
        parentKey: '/ns0:Root/ManyToMany/Year',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day',
                name: 'Day',
                schemaNodeDataType: 'None',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                    name: 'Date',
                    schemaNodeDataType: 'String',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'Date',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                    ],
                  },
                ],
                fullName: 'Day',
                parentKey: '/ns0:Root/ManyToMany/Year/Month',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                ],
              },
            ],
            fullName: 'Month',
            parentKey: '/ns0:Root/ManyToMany/Year',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/Year/Month': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year/Month',
        name: 'Month',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month/Day',
            name: 'Day',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                name: 'Date',
                schemaNodeDataType: 'String',
                normalizedDataType: 'String',
                properties: 'NotSpecified',
                fullName: 'Date',
                parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                nodeProperties: ['NotSpecified'],
                children: [],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                ],
              },
            ],
            fullName: 'Day',
            parentKey: '/ns0:Root/ManyToMany/Year/Month',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
            ],
          },
        ],
        fullName: 'Month',
        parentKey: '/ns0:Root/ManyToMany/Year',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/Year/Month',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year/Month',
          name: 'Month',
          schemaNodeDataType: 'None',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month/Day',
              name: 'Day',
              schemaNodeDataType: 'None',
              normalizedDataType: 'ComplexType',
              properties: 'Repeating',
              children: [
                {
                  key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                  name: 'Date',
                  schemaNodeDataType: 'String',
                  normalizedDataType: 'String',
                  properties: 'NotSpecified',
                  fullName: 'Date',
                  parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                  nodeProperties: ['NotSpecified'],
                  children: [],
                  pathToRoot: [
                    { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                    { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                    { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                  ],
                },
              ],
              fullName: 'Day',
              parentKey: '/ns0:Root/ManyToMany/Year/Month',
              nodeProperties: ['Repeating'],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
              ],
            },
          ],
          fullName: 'Month',
          parentKey: '/ns0:Root/ManyToMany/Year',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year/Month',
      },
    ],
  },
  'target-/ns0:Root/ManyToMany/Year': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year',
        name: 'Year',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day',
                name: 'Day',
                schemaNodeDataType: 'None',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                    name: 'Date',
                    schemaNodeDataType: 'String',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'Date',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                    ],
                  },
                ],
                fullName: 'Day',
                parentKey: '/ns0:Root/ManyToMany/Year/Month',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                ],
              },
            ],
            fullName: 'Month',
            parentKey: '/ns0:Root/ManyToMany/Year',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            ],
          },
        ],
        fullName: 'Year',
        parentKey: '/ns0:Root/ManyToMany',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
        ],
      },
      reactFlowKey: 'target-/ns0:Root/ManyToMany/Year',
    },
    inputs: {
      '0': [
        {
          node: {
            key: '/ns0:Root/ManyToMany/Year',
            name: 'Year',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month',
                name: 'Month',
                schemaNodeDataType: 'None',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day',
                    name: 'Day',
                    schemaNodeDataType: 'None',
                    normalizedDataType: 'ComplexType',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                        name: 'Date',
                        schemaNodeDataType: 'String',
                        normalizedDataType: 'String',
                        properties: 'NotSpecified',
                        fullName: 'Date',
                        parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                        nodeProperties: ['NotSpecified'],
                        children: [],
                        pathToRoot: [
                          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                          { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                          { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                          { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                        ],
                      },
                    ],
                    fullName: 'Day',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month',
                    nodeProperties: ['Repeating'],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                    ],
                  },
                ],
                fullName: 'Month',
                parentKey: '/ns0:Root/ManyToMany/Year',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                ],
              },
            ],
            fullName: 'Year',
            parentKey: '/ns0:Root/ManyToMany',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
            ],
          },
          reactFlowKey: 'source-/ns0:Root/ManyToMany/Year',
        },
      ],
    },
    outputs: [],
  },
  'source-/ns0:Root/ManyToMany/Year': {
    self: {
      node: {
        key: '/ns0:Root/ManyToMany/Year',
        name: 'Year',
        schemaNodeDataType: 'None',
        normalizedDataType: 'ComplexType',
        properties: 'Repeating',
        children: [
          {
            key: '/ns0:Root/ManyToMany/Year/Month',
            name: 'Month',
            schemaNodeDataType: 'None',
            normalizedDataType: 'ComplexType',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/ManyToMany/Year/Month/Day',
                name: 'Day',
                schemaNodeDataType: 'None',
                normalizedDataType: 'ComplexType',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                    name: 'Date',
                    schemaNodeDataType: 'String',
                    normalizedDataType: 'String',
                    properties: 'NotSpecified',
                    fullName: 'Date',
                    parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                    nodeProperties: ['NotSpecified'],
                    children: [],
                    pathToRoot: [
                      { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                      { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                      { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                      { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                    ],
                  },
                ],
                fullName: 'Day',
                parentKey: '/ns0:Root/ManyToMany/Year/Month',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                  { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                  { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                  { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                ],
              },
            ],
            fullName: 'Month',
            parentKey: '/ns0:Root/ManyToMany/Year',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
              { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
              { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
              { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
            ],
          },
        ],
        fullName: 'Year',
        parentKey: '/ns0:Root/ManyToMany',
        nodeProperties: ['Repeating'],
        pathToRoot: [
          { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
          { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
          { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
        ],
      },
      reactFlowKey: 'source-/ns0:Root/ManyToMany/Year',
    },
    inputs: { '0': [] },
    outputs: [
      {
        node: {
          key: '/ns0:Root/ManyToMany/Year',
          name: 'Year',
          schemaNodeDataType: 'None',
          normalizedDataType: 'ComplexType',
          properties: 'Repeating',
          children: [
            {
              key: '/ns0:Root/ManyToMany/Year/Month',
              name: 'Month',
              schemaNodeDataType: 'None',
              normalizedDataType: 'ComplexType',
              properties: 'Repeating',
              children: [
                {
                  key: '/ns0:Root/ManyToMany/Year/Month/Day',
                  name: 'Day',
                  schemaNodeDataType: 'None',
                  normalizedDataType: 'ComplexType',
                  properties: 'Repeating',
                  children: [
                    {
                      key: '/ns0:Root/ManyToMany/Year/Month/Day/Date',
                      name: 'Date',
                      schemaNodeDataType: 'String',
                      normalizedDataType: 'String',
                      properties: 'NotSpecified',
                      fullName: 'Date',
                      parentKey: '/ns0:Root/ManyToMany/Year/Month/Day',
                      nodeProperties: ['NotSpecified'],
                      children: [],
                      pathToRoot: [
                        { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                        { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                        { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                        { key: '/ns0:Root/ManyToMany/Year/Month/Day/Date', name: 'Date', fullName: 'Date', repeating: false },
                      ],
                    },
                  ],
                  fullName: 'Day',
                  parentKey: '/ns0:Root/ManyToMany/Year/Month',
                  nodeProperties: ['Repeating'],
                  pathToRoot: [
                    { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                    { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                    { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
                    { key: '/ns0:Root/ManyToMany/Year/Month/Day', name: 'Day', fullName: 'Day', repeating: true },
                  ],
                },
              ],
              fullName: 'Month',
              parentKey: '/ns0:Root/ManyToMany/Year',
              nodeProperties: ['Repeating'],
              pathToRoot: [
                { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
                { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
                { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
                { key: '/ns0:Root/ManyToMany/Year/Month', name: 'Month', fullName: 'Month', repeating: true },
              ],
            },
          ],
          fullName: 'Year',
          parentKey: '/ns0:Root/ManyToMany',
          nodeProperties: ['Repeating'],
          pathToRoot: [
            { key: '/ns0:Root', name: 'Root', fullName: 'ns0:Root', repeating: false },
            { key: '/ns0:Root/ManyToMany', name: 'ManyToMany', fullName: 'ManyToMany', repeating: false },
            { key: '/ns0:Root/ManyToMany/Year', name: 'Year', fullName: 'Year', repeating: true },
          ],
        },
        reactFlowKey: 'target-/ns0:Root/ManyToMany/Year',
      },
    ],
  },
} as ConnectionDictionary;
