import type { SchemaNodeExtended } from '../../models';

export const sourceSchemaNodes: SchemaNodeExtended[] = [
  {
    key: '/ns0:Root/Looping/Employee',
    name: 'Employee',
    type: 'Complex',
    properties: 'Repeating',
    children: [
      {
        key: '/ns0:Root/Looping/Employee/TelephoneNumber',
        name: 'TelephoneNumber',
        type: 'String',
        properties: 'None',
        qName: 'TelephoneNumber',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/TelephoneNumber',
            name: 'TelephoneNumber',
            qName: 'TelephoneNumber',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping/Employee/Name',
        name: 'Name',
        type: 'String',
        properties: 'None',
        qName: 'Name',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Name',
            name: 'Name',
            qName: 'Name',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping/Employee/Salary',
        name: 'Salary',
        type: 'Decimal',
        properties: 'None',
        qName: 'Salary',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Salary',
            name: 'Salary',
            qName: 'Salary',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping/Employee/Country',
        name: 'Country',
        type: 'String',
        properties: 'None',
        qName: 'Country',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Country',
            name: 'Country',
            qName: 'Country',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
        name: 'Dat_of_Birth',
        type: 'DateTime',
        properties: 'None',
        qName: 'Dat_of_Birth',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
            name: 'Dat_of_Birth',
            qName: 'Dat_of_Birth',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping/Employee/Address',
        name: 'Address',
        type: 'String',
        properties: 'None',
        qName: 'Address',
        parentKey: '/ns0:Root/Looping/Employee',
        nodeProperties: ['None'],
        children: [],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            qName: 'Employee',
            repeating: true,
          },
          {
            key: '/ns0:Root/Looping/Employee/Address',
            name: 'Address',
            qName: 'Address',
            repeating: false,
          },
        ],
      },
    ],
    qName: 'Employee',
    parentKey: '/ns0:Root/Looping',
    nodeProperties: ['Repeating'],
    pathToRoot: [
      {
        key: '/ns0:Root',
        name: 'Root',
        qName: 'ns0:Root',
        repeating: false,
      },
      {
        key: '/ns0:Root/Looping',
        name: 'Looping',
        qName: 'Looping',
        repeating: false,
      },
      {
        key: '/ns0:Root/Looping/Employee',
        name: 'Employee',
        qName: 'Employee',
        repeating: true,
      },
    ],
  },
  {
    key: '/ns0:Root/Looping/Employee/TelephoneNumber',
    name: 'TelephoneNumber',
    type: 'String',
    properties: 'None',
    qName: 'TelephoneNumber',
    parentKey: '/ns0:Root/Looping/Employee',
    nodeProperties: ['None'],
    children: [],
    pathToRoot: [
      {
        key: '/ns0:Root',
        name: 'Root',
        qName: 'ns0:Root',
        repeating: false,
      },
      {
        key: '/ns0:Root/Looping',
        name: 'Looping',
        qName: 'Looping',
        repeating: false,
      },
      {
        key: '/ns0:Root/Looping/Employee',
        name: 'Employee',
        qName: 'Employee',
        repeating: true,
      },
      {
        key: '/ns0:Root/Looping/Employee/TelephoneNumber',
        name: 'TelephoneNumber',
        qName: 'TelephoneNumber',
        repeating: false,
      },
    ],
  },
] as SchemaNodeExtended[];
