import type { ConnectionReference } from '../../common/models/workflow';
import type { Settings } from '../actions/bjsworkflow/settings';
import type { DependencyInfo, NodeInputs, NodeOperation, NodeOutputs, OutputInfo } from '../state/operation/operationMetadataSlice';
import type { WorkflowParameterDefinition } from '../state/workflowparameters/workflowparametersSlice';
import type { Expression, OperationManifest, OutputParameter, OutputParameters } from '@microsoft/logic-apps-shared';
import type { Dispatch } from '@reduxjs/toolkit';
export declare const toOutputInfo: (output: OutputParameter) => OutputInfo;
export declare const operationSupportsSplitOn: (isTrigger: boolean) => boolean;
export declare const removeAliasingKeyRedundancies: (openAPIkey: string) => string;
export declare const getUpdatedManifestForSplitOn: (manifest: OperationManifest, splitOn: string | undefined) => OperationManifest;
export declare const isSupportedSplitOnExpression: (expression: Expression) => boolean;
export declare const getSplitOnOptions: (outputs: NodeOutputs | undefined, isManifestBasedOperation: boolean) => string[];
export declare const getUpdatedManifestForSchemaDependency: (manifest: OperationManifest, inputs: NodeInputs) => OperationManifest;
export declare const updateOutputsForBatchingTrigger: (outputs: OutputParameters, splitOn: string | undefined) => OutputParameters;
export declare const loadDynamicOutputsInNode: (nodeId: string, isTrigger: boolean, operationInfo: NodeOperation, connectionReference: ConnectionReference | undefined, outputDependencies: Record<string, DependencyInfo>, nodeInputs: NodeInputs, settings: Settings, workflowParameters: Record<string, WorkflowParameterDefinition>, dispatch: Dispatch) => Promise<void>;
