export { default as sourceMockSchema } from './SourceSchema.json';
export { default as targetMockSchema } from './TargetSchema.json';
export { default as sourceMockJsonSchema } from './SourceSchemaJson.json';
export { default as targetMockJsonSchema } from './TargetSchemaJson.json';
export { default as comprehensiveSourceSchema } from './ComprehensiveSourceSchema.json';
export { default as comprehensiveTargetSchema } from './ComprehensiveTargetSchema.json';
export { default as playgroundSourceSchema } from './PlaygroundSourceSchema.json';
export { default as playgroundTargetSchema } from './PlaygroundTargetSchema.json';
export { default as deepNestedSequenceAndObject } from './DeepNestedSequenceAndObj.json';
