import type { LogicAppsV2 } from '@microsoft/logic-apps-shared';
import type { OutputMock } from '../../../../core/state/unitTest/unitTestInterfaces';
import type { MouseEventHandler } from 'react';
import type { ConnectDragPreview, ConnectDragSource } from 'react-dnd';
export interface ActionCardProps {
    active?: boolean;
    brandColor?: string;
    cloned?: boolean;
    connectorName?: string;
    drag: ConnectDragSource;
    dragPreview: ConnectDragPreview;
    errorMessages?: string[];
    icon?: string;
    id: string;
    isDragging?: boolean;
    isUnitTest?: boolean;
    isLoading?: boolean;
    isSelected?: boolean;
    nodeIndex?: number;
    readOnly?: boolean;
    rootRef?: React.RefObject<HTMLDivElement>;
    staticResultsEnabled?: boolean;
    title: string;
    onClick?(): void;
    onContextMenu?: MouseEventHandler<HTMLElement>;
    onDeleteClick?(): void;
    onCopyClick?(): void;
    runData?: LogicAppsV2.WorkflowRunAction | LogicAppsV2.WorkflowRunTrigger;
    setFocus?: boolean;
    nodeMockResults?: OutputMock;
    isMockSupported?: boolean;
    isLoadingDynamicData?: boolean;
    subtleBackground?: boolean;
    isScope?: boolean;
    collapsed?: boolean;
    handleCollapse?(): void;
}
export declare const ActionCard: React.FC<ActionCardProps>;
