// TODO (kmritta): Delete this file

import type { SchemaExtended } from '@microsoft/logic-apps-shared';

const mockTree: SchemaExtended = {
  name: 'Source.xsd',
  type: 'XML',
  targetNamespace: 'http://tempuri.org/source.xsd',
  namespaces: {
    ns0: 'http://tempuri.org/source.xsd',
    xs: 'http://www.w3.org/2001/XMLSchema',
  },
  schemaTreeRoot: {
    key: '/ns0:Root',
    name: 'Root',
    type: 'Complex',
    properties: 'None',
    children: [
      {
        key: '/ns0:Root/DirectTranslation',
        name: 'DirectTranslation',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/DirectTranslation/EmployeeID',
            name: 'EmployeeID',
            type: 'Decimal',
            properties: 'None',
            qName: 'EmployeeID',
            parentKey: '/ns0:Root/DirectTranslation',
            nodeProperties: ['None'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/DirectTranslation',
                name: 'DirectTranslation',
                qName: 'DirectTranslation',
                repeating: false,
              },
              {
                key: '/ns0:Root/DirectTranslation/EmployeeID',
                name: 'EmployeeID',
                qName: 'EmployeeID',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/DirectTranslation/EmployeeName',
            name: 'EmployeeName',
            type: 'String',
            properties: 'None',
            qName: 'EmployeeName',
            parentKey: '/ns0:Root/DirectTranslation',
            nodeProperties: ['None'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/DirectTranslation',
                name: 'DirectTranslation',
                qName: 'DirectTranslation',
                repeating: false,
              },
              {
                key: '/ns0:Root/DirectTranslation/EmployeeName',
                name: 'EmployeeName',
                qName: 'EmployeeName',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'DirectTranslation',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/DirectTranslation',
            name: 'DirectTranslation',
            qName: 'DirectTranslation',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/DataTranslation',
        name: 'DataTranslation',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/DataTranslation/Employee',
            name: 'Employee',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/DataTranslation/Employee/FirstName',
                name: 'FirstName',
                type: 'String',
                properties: 'None',
                qName: 'FirstName',
                parentKey: '/ns0:Root/DataTranslation/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation',
                    name: 'DataTranslation',
                    qName: 'DataTranslation',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee/FirstName',
                    name: 'FirstName',
                    qName: 'FirstName',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/DataTranslation/Employee/LastName',
                name: 'LastName',
                type: 'String',
                properties: 'None',
                qName: 'LastName',
                parentKey: '/ns0:Root/DataTranslation/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation',
                    name: 'DataTranslation',
                    qName: 'DataTranslation',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee/LastName',
                    name: 'LastName',
                    qName: 'LastName',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/DataTranslation/Employee/EmploymentStatus',
                name: 'EmploymentStatus',
                type: 'Bool',
                properties: 'None',
                qName: 'EmploymentStatus',
                parentKey: '/ns0:Root/DataTranslation/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation',
                    name: 'DataTranslation',
                    qName: 'DataTranslation',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/DataTranslation/Employee/EmploymentStatus',
                    name: 'EmploymentStatus',
                    qName: 'EmploymentStatus',
                    repeating: false,
                  },
                ],
              },
            ],
            qName: 'Employee',
            parentKey: '/ns0:Root/DataTranslation',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/DataTranslation',
                name: 'DataTranslation',
                qName: 'DataTranslation',
                repeating: false,
              },
              {
                key: '/ns0:Root/DataTranslation/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'DataTranslation',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/DataTranslation',
            name: 'DataTranslation',
            qName: 'DataTranslation',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/CumulativeExpression',
        name: 'CumulativeExpression',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/CumulativeExpression/Population',
            name: 'Population',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/CumulativeExpression/Population/State',
                name: 'State',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/CumulativeExpression/Population/State/Name',
                    name: 'Name',
                    type: 'String',
                    properties: 'None',
                    qName: 'Name',
                    parentKey: '/ns0:Root/CumulativeExpression/Population/State',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression',
                        name: 'CumulativeExpression',
                        qName: 'CumulativeExpression',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population',
                        name: 'Population',
                        qName: 'Population',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State',
                        name: 'State',
                        qName: 'State',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/Name',
                        name: 'Name',
                        qName: 'Name',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/CumulativeExpression/Population/State/County',
                    name: 'County',
                    type: 'Complex',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/County/Name',
                        name: 'Name',
                        type: 'String',
                        properties: 'None',
                        qName: 'Name',
                        parentKey: '/ns0:Root/CumulativeExpression/Population/State/County',
                        nodeProperties: ['None'],
                        children: [],
                        pathToRoot: [
                          {
                            key: '/ns0:Root',
                            name: 'Root',
                            qName: 'ns0:Root',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression',
                            name: 'CumulativeExpression',
                            qName: 'CumulativeExpression',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population',
                            name: 'Population',
                            qName: 'Population',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State',
                            name: 'State',
                            qName: 'State',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County',
                            name: 'County',
                            qName: 'County',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Name',
                            name: 'Name',
                            qName: 'Name',
                            repeating: false,
                          },
                        ],
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                        name: 'Person',
                        type: 'Complex',
                        properties: 'Repeating',
                        children: [
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Name',
                            name: 'Name',
                            type: 'String',
                            properties: 'None',
                            qName: 'Name',
                            parentKey: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                            nodeProperties: ['None'],
                            children: [],
                            pathToRoot: [
                              {
                                key: '/ns0:Root',
                                name: 'Root',
                                qName: 'ns0:Root',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression',
                                name: 'CumulativeExpression',
                                qName: 'CumulativeExpression',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population',
                                name: 'Population',
                                qName: 'Population',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State',
                                name: 'State',
                                qName: 'State',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County',
                                name: 'County',
                                qName: 'County',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                                name: 'Person',
                                qName: 'Person',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Name',
                                name: 'Name',
                                qName: 'Name',
                                repeating: false,
                              },
                            ],
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Age',
                            name: 'Age',
                            type: 'String',
                            properties: 'None',
                            qName: 'Age',
                            parentKey: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                            nodeProperties: ['None'],
                            children: [],
                            pathToRoot: [
                              {
                                key: '/ns0:Root',
                                name: 'Root',
                                qName: 'ns0:Root',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression',
                                name: 'CumulativeExpression',
                                qName: 'CumulativeExpression',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population',
                                name: 'Population',
                                qName: 'Population',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State',
                                name: 'State',
                                qName: 'State',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County',
                                name: 'County',
                                qName: 'County',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                                name: 'Person',
                                qName: 'Person',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Age',
                                name: 'Age',
                                qName: 'Age',
                                repeating: false,
                              },
                            ],
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                            name: 'Sex',
                            type: 'Complex',
                            properties: 'None',
                            children: [
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Male',
                                name: 'Male',
                                type: 'Bool',
                                properties: 'None',
                                qName: 'Male',
                                parentKey: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                                nodeProperties: ['None'],
                                children: [],
                                pathToRoot: [
                                  {
                                    key: '/ns0:Root',
                                    name: 'Root',
                                    qName: 'ns0:Root',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression',
                                    name: 'CumulativeExpression',
                                    qName: 'CumulativeExpression',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population',
                                    name: 'Population',
                                    qName: 'Population',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State',
                                    name: 'State',
                                    qName: 'State',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County',
                                    name: 'County',
                                    qName: 'County',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                                    name: 'Person',
                                    qName: 'Person',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                                    name: 'Sex',
                                    qName: 'Sex',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Male',
                                    name: 'Male',
                                    qName: 'Male',
                                    repeating: false,
                                  },
                                ],
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Female',
                                name: 'Female',
                                type: 'Bool',
                                properties: 'None',
                                qName: 'Female',
                                parentKey: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                                nodeProperties: ['None'],
                                children: [],
                                pathToRoot: [
                                  {
                                    key: '/ns0:Root',
                                    name: 'Root',
                                    qName: 'ns0:Root',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression',
                                    name: 'CumulativeExpression',
                                    qName: 'CumulativeExpression',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population',
                                    name: 'Population',
                                    qName: 'Population',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State',
                                    name: 'State',
                                    qName: 'State',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County',
                                    name: 'County',
                                    qName: 'County',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                                    name: 'Person',
                                    qName: 'Person',
                                    repeating: true,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                                    name: 'Sex',
                                    qName: 'Sex',
                                    repeating: false,
                                  },
                                  {
                                    key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex/Female',
                                    name: 'Female',
                                    qName: 'Female',
                                    repeating: false,
                                  },
                                ],
                              },
                            ],
                            qName: 'Sex',
                            parentKey: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                            nodeProperties: ['None'],
                            pathToRoot: [
                              {
                                key: '/ns0:Root',
                                name: 'Root',
                                qName: 'ns0:Root',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression',
                                name: 'CumulativeExpression',
                                qName: 'CumulativeExpression',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population',
                                name: 'Population',
                                qName: 'Population',
                                repeating: false,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State',
                                name: 'State',
                                qName: 'State',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County',
                                name: 'County',
                                qName: 'County',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                                name: 'Person',
                                qName: 'Person',
                                repeating: true,
                              },
                              {
                                key: '/ns0:Root/CumulativeExpression/Population/State/County/Person/Sex',
                                name: 'Sex',
                                qName: 'Sex',
                                repeating: false,
                              },
                            ],
                          },
                        ],
                        qName: 'Person',
                        parentKey: '/ns0:Root/CumulativeExpression/Population/State/County',
                        nodeProperties: ['Repeating'],
                        pathToRoot: [
                          {
                            key: '/ns0:Root',
                            name: 'Root',
                            qName: 'ns0:Root',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression',
                            name: 'CumulativeExpression',
                            qName: 'CumulativeExpression',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population',
                            name: 'Population',
                            qName: 'Population',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State',
                            name: 'State',
                            qName: 'State',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County',
                            name: 'County',
                            qName: 'County',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/CumulativeExpression/Population/State/County/Person',
                            name: 'Person',
                            qName: 'Person',
                            repeating: true,
                          },
                        ],
                      },
                    ],
                    qName: 'County',
                    parentKey: '/ns0:Root/CumulativeExpression/Population/State',
                    nodeProperties: ['Repeating'],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression',
                        name: 'CumulativeExpression',
                        qName: 'CumulativeExpression',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population',
                        name: 'Population',
                        qName: 'Population',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State',
                        name: 'State',
                        qName: 'State',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/CumulativeExpression/Population/State/County',
                        name: 'County',
                        qName: 'County',
                        repeating: true,
                      },
                    ],
                  },
                ],
                qName: 'State',
                parentKey: '/ns0:Root/CumulativeExpression/Population',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/CumulativeExpression',
                    name: 'CumulativeExpression',
                    qName: 'CumulativeExpression',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/CumulativeExpression/Population',
                    name: 'Population',
                    qName: 'Population',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/CumulativeExpression/Population/State',
                    name: 'State',
                    qName: 'State',
                    repeating: true,
                  },
                ],
              },
            ],
            qName: 'Population',
            parentKey: '/ns0:Root/CumulativeExpression',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/CumulativeExpression',
                name: 'CumulativeExpression',
                qName: 'CumulativeExpression',
                repeating: false,
              },
              {
                key: '/ns0:Root/CumulativeExpression/Population',
                name: 'Population',
                qName: 'Population',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'CumulativeExpression',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/CumulativeExpression',
            name: 'CumulativeExpression',
            qName: 'CumulativeExpression',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/ConditionalMapping',
        name: 'ConditionalMapping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/ConditionalMapping/ItemPrice',
            name: 'ItemPrice',
            type: 'Decimal',
            properties: 'None',
            qName: 'ItemPrice',
            parentKey: '/ns0:Root/ConditionalMapping',
            nodeProperties: ['None'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalMapping',
                name: 'ConditionalMapping',
                qName: 'ConditionalMapping',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalMapping/ItemPrice',
                name: 'ItemPrice',
                qName: 'ItemPrice',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/ConditionalMapping/ItemQuantity',
            name: 'ItemQuantity',
            type: 'Decimal',
            properties: 'None',
            qName: 'ItemQuantity',
            parentKey: '/ns0:Root/ConditionalMapping',
            nodeProperties: ['None'],
            children: [],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalMapping',
                name: 'ConditionalMapping',
                qName: 'ConditionalMapping',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalMapping/ItemQuantity',
                name: 'ItemQuantity',
                qName: 'ItemQuantity',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'ConditionalMapping',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ConditionalMapping',
            name: 'ConditionalMapping',
            qName: 'ConditionalMapping',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/Looping',
        name: 'Looping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/Looping/Employee',
            name: 'Employee',
            type: 'Complex',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                name: 'TelephoneNumber',
                type: 'String',
                properties: 'None',
                qName: 'TelephoneNumber',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/TelephoneNumber',
                    name: 'TelephoneNumber',
                    qName: 'TelephoneNumber',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Name',
                name: 'Name',
                type: 'String',
                properties: 'None',
                qName: 'Name',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Name',
                    name: 'Name',
                    qName: 'Name',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Salary',
                name: 'Salary',
                type: 'Decimal',
                properties: 'None',
                qName: 'Salary',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Salary',
                    name: 'Salary',
                    qName: 'Salary',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Country',
                name: 'Country',
                type: 'String',
                properties: 'None',
                qName: 'Country',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Country',
                    name: 'Country',
                    qName: 'Country',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                name: 'Dat_of_Birth',
                type: 'DateTime',
                properties: 'None',
                qName: 'Dat_of_Birth',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Dat_of_Birth',
                    name: 'Dat_of_Birth',
                    qName: 'Dat_of_Birth',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/Employee/Address',
                name: 'Address',
                type: 'String',
                properties: 'None',
                qName: 'Address',
                parentKey: '/ns0:Root/Looping/Employee',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee',
                    name: 'Employee',
                    qName: 'Employee',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/Looping/Employee/Address',
                    name: 'Address',
                    qName: 'Address',
                    repeating: false,
                  },
                ],
              },
            ],
            qName: 'Employee',
            parentKey: '/ns0:Root/Looping',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/Employee',
                name: 'Employee',
                qName: 'Employee',
                repeating: true,
              },
            ],
          },
          {
            key: '/ns0:Root/Looping/VehicleTrips',
            name: 'VehicleTrips',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                name: 'Vehicle',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleID',
                    name: 'VehicleID',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleID',
                    parentKey: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping',
                        name: 'Looping',
                        qName: 'Looping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips',
                        name: 'VehicleTrips',
                        qName: 'VehicleTrips',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                        name: 'Vehicle',
                        qName: 'Vehicle',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleID',
                        name: 'VehicleID',
                        qName: 'VehicleID',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleRegistration',
                    name: 'VehicleRegistration',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleRegistration',
                    parentKey: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping',
                        name: 'Looping',
                        qName: 'Looping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips',
                        name: 'VehicleTrips',
                        qName: 'VehicleTrips',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                        name: 'Vehicle',
                        qName: 'Vehicle',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Vehicle/VehicleRegistration',
                        name: 'VehicleRegistration',
                        qName: 'VehicleRegistration',
                        repeating: false,
                      },
                    ],
                  },
                ],
                qName: 'Vehicle',
                parentKey: '/ns0:Root/Looping/VehicleTrips',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips',
                    name: 'VehicleTrips',
                    qName: 'VehicleTrips',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Vehicle',
                    name: 'Vehicle',
                    qName: 'Vehicle',
                    repeating: true,
                  },
                ],
              },
              {
                key: '/ns0:Root/Looping/VehicleTrips/Trips',
                name: 'Trips',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/VehicleId',
                    name: 'VehicleId',
                    type: 'String',
                    properties: 'None',
                    qName: 'VehicleId',
                    parentKey: '/ns0:Root/Looping/VehicleTrips/Trips',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping',
                        name: 'Looping',
                        qName: 'Looping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips',
                        name: 'VehicleTrips',
                        qName: 'VehicleTrips',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips',
                        name: 'Trips',
                        qName: 'Trips',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips/VehicleId',
                        name: 'VehicleId',
                        qName: 'VehicleId',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/Distance',
                    name: 'Distance',
                    type: 'Decimal',
                    properties: 'None',
                    qName: 'Distance',
                    parentKey: '/ns0:Root/Looping/VehicleTrips/Trips',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping',
                        name: 'Looping',
                        qName: 'Looping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips',
                        name: 'VehicleTrips',
                        qName: 'VehicleTrips',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips',
                        name: 'Trips',
                        qName: 'Trips',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips/Distance',
                        name: 'Distance',
                        qName: 'Distance',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips/Duration',
                    name: 'Duration',
                    type: 'Decimal',
                    properties: 'None',
                    qName: 'Duration',
                    parentKey: '/ns0:Root/Looping/VehicleTrips/Trips',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping',
                        name: 'Looping',
                        qName: 'Looping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips',
                        name: 'VehicleTrips',
                        qName: 'VehicleTrips',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips',
                        name: 'Trips',
                        qName: 'Trips',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/Looping/VehicleTrips/Trips/Duration',
                        name: 'Duration',
                        qName: 'Duration',
                        repeating: false,
                      },
                    ],
                  },
                ],
                qName: 'Trips',
                parentKey: '/ns0:Root/Looping/VehicleTrips',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping',
                    name: 'Looping',
                    qName: 'Looping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips',
                    name: 'VehicleTrips',
                    qName: 'VehicleTrips',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/Looping/VehicleTrips/Trips',
                    name: 'Trips',
                    qName: 'Trips',
                    repeating: true,
                  },
                ],
              },
            ],
            qName: 'VehicleTrips',
            parentKey: '/ns0:Root/Looping',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping',
                name: 'Looping',
                qName: 'Looping',
                repeating: false,
              },
              {
                key: '/ns0:Root/Looping/VehicleTrips',
                name: 'VehicleTrips',
                qName: 'VehicleTrips',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'Looping',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/Looping',
            name: 'Looping',
            qName: 'Looping',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/ConditionalLooping',
        name: 'ConditionalLooping',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
            name: 'FlatterCatalog',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                name: 'Product',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Name',
                    name: 'Name',
                    type: 'String',
                    properties: 'None',
                    qName: 'Name',
                    parentKey: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping',
                        name: 'ConditionalLooping',
                        qName: 'ConditionalLooping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                        name: 'FlatterCatalog',
                        qName: 'FlatterCatalog',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                        name: 'Product',
                        qName: 'ns0:Product',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Name',
                        name: 'Name',
                        qName: 'Name',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/SKU',
                    name: 'SKU',
                    type: 'String',
                    properties: 'None',
                    qName: 'SKU',
                    parentKey: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping',
                        name: 'ConditionalLooping',
                        qName: 'ConditionalLooping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                        name: 'FlatterCatalog',
                        qName: 'FlatterCatalog',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                        name: 'Product',
                        qName: 'ns0:Product',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/SKU',
                        name: 'SKU',
                        qName: 'SKU',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Price',
                    name: 'Price',
                    type: 'String',
                    properties: 'None',
                    qName: 'Price',
                    parentKey: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping',
                        name: 'ConditionalLooping',
                        qName: 'ConditionalLooping',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                        name: 'FlatterCatalog',
                        qName: 'FlatterCatalog',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                        name: 'Product',
                        qName: 'ns0:Product',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product/Price',
                        name: 'Price',
                        qName: 'Price',
                        repeating: false,
                      },
                    ],
                  },
                ],
                qName: 'ns0:Product',
                parentKey: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping',
                    name: 'ConditionalLooping',
                    qName: 'ConditionalLooping',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                    name: 'FlatterCatalog',
                    qName: 'FlatterCatalog',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/ConditionalLooping/FlatterCatalog/ns0:Product',
                    name: 'Product',
                    qName: 'ns0:Product',
                    repeating: true,
                  },
                ],
              },
            ],
            qName: 'FlatterCatalog',
            parentKey: '/ns0:Root/ConditionalLooping',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalLooping',
                name: 'ConditionalLooping',
                qName: 'ConditionalLooping',
                repeating: false,
              },
              {
                key: '/ns0:Root/ConditionalLooping/FlatterCatalog',
                name: 'FlatterCatalog',
                qName: 'FlatterCatalog',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'ConditionalLooping',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/ConditionalLooping',
            name: 'ConditionalLooping',
            qName: 'ConditionalLooping',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/LoopingWithIndex',
        name: 'LoopingWithIndex',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/LoopingWithIndex/WeatherReport',
            name: 'WeatherReport',
            type: 'Complex',
            properties: 'Repeating',
            children: [
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Pressure',
                name: 'Pressure',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@Pressure',
                parentKey: '/ns0:Root/LoopingWithIndex/WeatherReport',
                nodeProperties: ['Attribute'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex',
                    name: 'LoopingWithIndex',
                    qName: 'LoopingWithIndex',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport',
                    name: 'WeatherReport',
                    qName: 'WeatherReport',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Pressure',
                    name: 'Pressure',
                    qName: '@Pressure',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@WindSpeed',
                name: 'WindSpeed',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@WindSpeed',
                parentKey: '/ns0:Root/LoopingWithIndex/WeatherReport',
                nodeProperties: ['Attribute'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex',
                    name: 'LoopingWithIndex',
                    qName: 'LoopingWithIndex',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport',
                    name: 'WeatherReport',
                    qName: 'WeatherReport',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport/@WindSpeed',
                    name: 'WindSpeed',
                    qName: '@WindSpeed',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Temperature',
                name: 'Temperature',
                type: 'Decimal',
                properties: 'Attribute',
                qName: '@Temperature',
                parentKey: '/ns0:Root/LoopingWithIndex/WeatherReport',
                nodeProperties: ['Attribute'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex',
                    name: 'LoopingWithIndex',
                    qName: 'LoopingWithIndex',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport',
                    name: 'WeatherReport',
                    qName: 'WeatherReport',
                    repeating: true,
                  },
                  {
                    key: '/ns0:Root/LoopingWithIndex/WeatherReport/@Temperature',
                    name: 'Temperature',
                    qName: '@Temperature',
                    repeating: false,
                  },
                ],
              },
            ],
            qName: 'WeatherReport',
            parentKey: '/ns0:Root/LoopingWithIndex',
            nodeProperties: ['Repeating'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/LoopingWithIndex',
                name: 'LoopingWithIndex',
                qName: 'LoopingWithIndex',
                repeating: false,
              },
              {
                key: '/ns0:Root/LoopingWithIndex/WeatherReport',
                name: 'WeatherReport',
                qName: 'WeatherReport',
                repeating: true,
              },
            ],
          },
        ],
        qName: 'LoopingWithIndex',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/LoopingWithIndex',
            name: 'LoopingWithIndex',
            qName: 'LoopingWithIndex',
            repeating: false,
          },
        ],
      },
      {
        key: '/ns0:Root/NameValueTransforms',
        name: 'NameValueTransforms',
        type: 'Complex',
        properties: 'None',
        children: [
          {
            key: '/ns0:Root/NameValueTransforms/Catalog',
            name: 'Catalog',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                name: 'Product',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                    name: 'Field',
                    type: 'Complex',
                    properties: 'Repeating',
                    children: [
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Name',
                        name: 'Name',
                        type: 'String',
                        properties: 'None',
                        qName: 'Name',
                        parentKey: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                        nodeProperties: ['None'],
                        children: [],
                        pathToRoot: [
                          {
                            key: '/ns0:Root',
                            name: 'Root',
                            qName: 'ns0:Root',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms',
                            name: 'NameValueTransforms',
                            qName: 'NameValueTransforms',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog',
                            name: 'Catalog',
                            qName: 'Catalog',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                            name: 'Product',
                            qName: 'Product',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                            name: 'Field',
                            qName: 'Field',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Name',
                            name: 'Name',
                            qName: 'Name',
                            repeating: false,
                          },
                        ],
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Value',
                        name: 'Value',
                        type: 'String',
                        properties: 'None',
                        qName: 'Value',
                        parentKey: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                        nodeProperties: ['None'],
                        children: [],
                        pathToRoot: [
                          {
                            key: '/ns0:Root',
                            name: 'Root',
                            qName: 'ns0:Root',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms',
                            name: 'NameValueTransforms',
                            qName: 'NameValueTransforms',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog',
                            name: 'Catalog',
                            qName: 'Catalog',
                            repeating: false,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                            name: 'Product',
                            qName: 'Product',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                            name: 'Field',
                            qName: 'Field',
                            repeating: true,
                          },
                          {
                            key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field/Value',
                            name: 'Value',
                            qName: 'Value',
                            repeating: false,
                          },
                        ],
                      },
                    ],
                    qName: 'Field',
                    parentKey: '/ns0:Root/NameValueTransforms/Catalog/Product',
                    nodeProperties: ['Repeating'],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog',
                        name: 'Catalog',
                        qName: 'Catalog',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                        name: 'Product',
                        qName: 'Product',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/Catalog/Product/Field',
                        name: 'Field',
                        qName: 'Field',
                        repeating: true,
                      },
                    ],
                  },
                ],
                qName: 'Product',
                parentKey: '/ns0:Root/NameValueTransforms/Catalog',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms',
                    name: 'NameValueTransforms',
                    qName: 'NameValueTransforms',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/Catalog',
                    name: 'Catalog',
                    qName: 'Catalog',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/Catalog/Product',
                    name: 'Product',
                    qName: 'Product',
                    repeating: true,
                  },
                ],
              },
            ],
            qName: 'Catalog',
            parentKey: '/ns0:Root/NameValueTransforms',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/NameValueTransforms',
                name: 'NameValueTransforms',
                qName: 'NameValueTransforms',
                repeating: false,
              },
              {
                key: '/ns0:Root/NameValueTransforms/Catalog',
                name: 'Catalog',
                qName: 'Catalog',
                repeating: false,
              },
            ],
          },
          {
            key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
            name: 'PurchaseOrderStatus',
            type: 'Complex',
            properties: 'None',
            children: [
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ShipperName',
                name: 'ShipperName',
                type: 'String',
                properties: 'None',
                qName: 'ShipperName',
                parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms',
                    name: 'NameValueTransforms',
                    qName: 'NameValueTransforms',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                    name: 'PurchaseOrderStatus',
                    qName: 'PurchaseOrderStatus',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ShipperName',
                    name: 'ShipperName',
                    qName: 'ShipperName',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ServiceLevel',
                name: 'ServiceLevel',
                type: 'String',
                properties: 'None',
                qName: 'ServiceLevel',
                parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms',
                    name: 'NameValueTransforms',
                    qName: 'NameValueTransforms',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                    name: 'PurchaseOrderStatus',
                    qName: 'PurchaseOrderStatus',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ServiceLevel',
                    name: 'ServiceLevel',
                    qName: 'ServiceLevel',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/DateShipped',
                name: 'DateShipped',
                type: 'String',
                properties: 'None',
                qName: 'DateShipped',
                parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                nodeProperties: ['None'],
                children: [],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms',
                    name: 'NameValueTransforms',
                    qName: 'NameValueTransforms',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                    name: 'PurchaseOrderStatus',
                    qName: 'PurchaseOrderStatus',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/DateShipped',
                    name: 'DateShipped',
                    qName: 'DateShipped',
                    repeating: false,
                  },
                ],
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                name: 'LineItem',
                type: 'Complex',
                properties: 'Repeating',
                children: [
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/ItemNumber',
                    name: 'ItemNumber',
                    type: 'String',
                    properties: 'None',
                    qName: 'ItemNumber',
                    parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                        name: 'PurchaseOrderStatus',
                        qName: 'PurchaseOrderStatus',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                        name: 'LineItem',
                        qName: 'ns0:LineItem',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/ItemNumber',
                        name: 'ItemNumber',
                        qName: 'ItemNumber',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityOrdered',
                    name: 'QuantityOrdered',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityOrdered',
                    parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                        name: 'PurchaseOrderStatus',
                        qName: 'PurchaseOrderStatus',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                        name: 'LineItem',
                        qName: 'ns0:LineItem',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityOrdered',
                        name: 'QuantityOrdered',
                        qName: 'QuantityOrdered',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityShipped',
                    name: 'QuantityShipped',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityShipped',
                    parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                        name: 'PurchaseOrderStatus',
                        qName: 'PurchaseOrderStatus',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                        name: 'LineItem',
                        qName: 'ns0:LineItem',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityShipped',
                        name: 'QuantityShipped',
                        qName: 'QuantityShipped',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityBackordered',
                    name: 'QuantityBackordered',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityBackordered',
                    parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                        name: 'PurchaseOrderStatus',
                        qName: 'PurchaseOrderStatus',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                        name: 'LineItem',
                        qName: 'ns0:LineItem',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityBackordered',
                        name: 'QuantityBackordered',
                        qName: 'QuantityBackordered',
                        repeating: false,
                      },
                    ],
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityCancelled',
                    name: 'QuantityCancelled',
                    type: 'String',
                    properties: 'None',
                    qName: 'QuantityCancelled',
                    parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    nodeProperties: ['None'],
                    children: [],
                    pathToRoot: [
                      {
                        key: '/ns0:Root',
                        name: 'Root',
                        qName: 'ns0:Root',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms',
                        name: 'NameValueTransforms',
                        qName: 'NameValueTransforms',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                        name: 'PurchaseOrderStatus',
                        qName: 'PurchaseOrderStatus',
                        repeating: false,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                        name: 'LineItem',
                        qName: 'ns0:LineItem',
                        repeating: true,
                      },
                      {
                        key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem/QuantityCancelled',
                        name: 'QuantityCancelled',
                        qName: 'QuantityCancelled',
                        repeating: false,
                      },
                    ],
                  },
                ],
                qName: 'ns0:LineItem',
                parentKey: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                nodeProperties: ['Repeating'],
                pathToRoot: [
                  {
                    key: '/ns0:Root',
                    name: 'Root',
                    qName: 'ns0:Root',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms',
                    name: 'NameValueTransforms',
                    qName: 'NameValueTransforms',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                    name: 'PurchaseOrderStatus',
                    qName: 'PurchaseOrderStatus',
                    repeating: false,
                  },
                  {
                    key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus/ns0:LineItem',
                    name: 'LineItem',
                    qName: 'ns0:LineItem',
                    repeating: true,
                  },
                ],
              },
            ],
            qName: 'PurchaseOrderStatus',
            parentKey: '/ns0:Root/NameValueTransforms',
            nodeProperties: ['None'],
            pathToRoot: [
              {
                key: '/ns0:Root',
                name: 'Root',
                qName: 'ns0:Root',
                repeating: false,
              },
              {
                key: '/ns0:Root/NameValueTransforms',
                name: 'NameValueTransforms',
                qName: 'NameValueTransforms',
                repeating: false,
              },
              {
                key: '/ns0:Root/NameValueTransforms/PurchaseOrderStatus',
                name: 'PurchaseOrderStatus',
                qName: 'PurchaseOrderStatus',
                repeating: false,
              },
            ],
          },
        ],
        qName: 'NameValueTransforms',
        parentKey: '/ns0:Root',
        nodeProperties: ['None'],
        pathToRoot: [
          {
            key: '/ns0:Root',
            name: 'Root',
            qName: 'ns0:Root',
            repeating: false,
          },
          {
            key: '/ns0:Root/NameValueTransforms',
            name: 'NameValueTransforms',
            qName: 'NameValueTransforms',
            repeating: false,
          },
        ],
      },
    ],
    qName: 'ns0:Root',
    nodeProperties: ['None'],
    pathToRoot: [
      {
        key: '/ns0:Root',
        name: 'Root',
        qName: 'ns0:Root',
        repeating: false,
      },
    ],
  },
};

export default mockTree;
