name: 'base-coverage'

on:
  push:
    branches: [main]
jobs:
  base-coverage:
    runs-on: ubuntu-latest   
    steps:
        - name: 'Checkout Github Action'
          uses: actions/checkout@master

        - name: Cache turbo build setup
          uses: actions/cache@v4
          with:
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-

        - name: Set up Node.js 
          uses: actions/setup-node@v1
          with:
            node-version: 20.x  

        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 6.x
            cache: true

        - uses: pnpm/action-setup@v3
          with:
            version: 8
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --strict-peer-dependencies]   

        - run: pnpm turbo run test:lib --cache-dir=.turbo 
        - name: Create code coverage report
          run: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            reportgenerator -reports:"libs/*/coverage/cobertura-coverage.xml" -targetdir:CodeCoverage -reporttypes:'MarkdownSummaryGithub,Cobertura'

        - uses: clearlyip/code-coverage-report-action@v4
          with:
            #Location of the generated coverage file
            filename: 'CodeCoverage/Cobertura.xml'
        - name: Write to Job Summary
          run: cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY