name: Generate Coverage Report

on:
#   push:
#     branches: [coverageReport]
  pull_request:
    branches: [main, dev/*, hotfix/*]
jobs:
#   base-coverage:
#     runs-on: ubuntu-latest

#     steps:
#       # checkout the repo
#       - name: 'Checkout Github Action'
#         uses: actions/checkout@master
#         with:
#             ref: main

#       - name: Set up Node.js 
#         uses: actions/setup-node@v1
#         with:
#           node-version: 20.x

#       - uses: pnpm/action-setup@v3
#         with:
#           version: 8
#           run_install: |
#             - recursive: true
#               args: [--frozen-lockfile, --strict-peer-dependencies]
            
#       - run: turbo run test:lib

  pr-coverage:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write    
    steps:
        - name: 'Checkout Github Action'
          uses: actions/checkout@master

        - name: Cache turbo build setup
          uses: actions/cache@v4
          with:
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-

        - name: Set up Node.js 
          uses: actions/setup-node@v1
          with:
            node-version: 20.x  

        - uses: pnpm/action-setup@v3
          with:
            version: 8
            run_install: |
              - recursive: true
                args: [--frozen-lockfile, --strict-peer-dependencies]   

        - run: pnpm turbo run test:lib --cache-dir=.turbo 
        - run: |
            chmod +x ./merge-lcov.sh
            ./merge-lcov.sh
          shell: bash
        
        - run: pnpm lcov-result-merger 'libs/*/coverage/lcov.info' './coverage'
        - name: Setup LCOV
          uses: hrishikesh-kadam/setup-lcov@v1

        - name: Report code coverage
          uses: zgosalvez/github-actions-report-lcov@v3
          with:
            coverage-files: "**/coverage/lcov.info"
            minimum-coverage: 0
            artifact-name: code-coverage-report
            github-token: ${{ secrets.GITHUB_TOKEN }}
            working-directory: ./libs
            update-comment: true