name: Deploy Documentation

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed, labeled]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: |
      (
        github.event_name == 'push' 
        || (github.event_name == 'pull_request' && github.event.action != 'closed') 
        || (github.event.label.name == 'Documentation')
      ) 
      && github.actor != 'csigs'
      &&  github.actor != 'azure-logic-apps-automation' 
      && (contains(github.event.pull_request.labels.*.name, 'Documentation') || github.event_name == 'push')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-docs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-docs-

      - name: Set up Node.js version 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, turbo, typescript]
              
      - run: turbo run build:docs

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          skip_app_build: true
          app_build_command: 'cd docs && npm run build'
          app_location: 'apps/docs/build'
          output_location: 'apps/docs/build'

  close_pull_request_job:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed') && github.actor != 'csigs' &&  github.actor != 'azure-logic-apps-automation'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: 'apps/docs/build'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
