name: Correct package-lock.json Version Check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: mansona/npm-lockfile-version@v1
