name: Azure Publish

on:
  repository_dispatch:
    types: [release_resolution_service]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_PAT }}
          PACKAGEJSON_DIR: './libs/services/resolution-service'
        with:
          bump-policy: 'ignore'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          tag-prefix: 'resolution-service@v'

      - run: npm ci
      - run: npm run build:resolution-service

      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: ${{ secrets.PUBLISHING_PAT }}
          working-directory: './dist/libs/services/resolution-service'

      - run: cd ./dist/libs/services/resolution-service && npm publish
