name: Risk Label Present
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            Risk:Low
            Risk:Medium
            Risk:High
