name: Release Production Templates
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: Templates
    name: Build and Deploy Job
    permissions:
        id-token: write
        contents: read
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - uses: pnpm/action-setup@v3
      with:
        version: 9.1.3
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Build Templates Folder
      run: pnpm run templates --download-images --subdirectory logicapps

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_TEMPLATES_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TEMPLATES_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_TEMPLATES_SUBSCRIPTION_ID }}

    - name: "Upload Logic Apps Templates to Azure Blob Storage"
      if: ${{ !cancelled() }}
      shell: bash
      run: |
          az storage blob upload-batch --account-name workflowtemplates --auth-mode key --overwrite True -d templates -s "./libs/logic-apps-shared/src/designer-client-services/lib/templates"
          echo "Templates are uploaded to the storage account - workflowtemplates"
