name: Release Production Templates
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
  
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: Templates
    name: Build and Deploy Job
    permissions:
        id-token: write
        contents: read

    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 24.x
        package-manager-cache: false

    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Build Templates Folder
      run: pnpm run templates --download-images --subdirectory logicapps

    - name: Azure login
      uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
      with:
        client-id: ${{ secrets.AZURE_TEMPLATES_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TEMPLATES_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_TEMPLATES_SUBSCRIPTION_ID }}

    - name: "Upload Logic Apps Templates to Azure Blob Storage"
      if: ${{ !cancelled() }}
      shell: bash
      run: |
          az storage blob upload-batch --account-name workflowtemplates --auth-mode login --overwrite True -d templates -s "./libs/logic-apps-shared/src/designer-client-services/lib/templates"
          echo "Templates are uploaded to the storage account - workflowtemplates"
