export declare const useConnectionPanelSelectedNodeIds: () => string[];
export declare const useCurrentPanelMode: () => "Error" | "Connection" | "Discovery" | "Operation" | "NodeSearch" | "WorkflowParameters" | "Assertions";
export declare const useDiscoveryPanelSelectedOperationGroupId: () => string;
export declare const useDiscoveryPanelSelectedOperationId: () => string;
export declare const useDiscoveryPanelSelectedNodeIds: () => string[];
export declare const useDiscoveryPanelIsAddingTrigger: () => boolean;
export declare const useDiscoveryPanelIsParallelBranch: () => boolean;
export declare const useDiscoveryPanelRelationshipIds: () => import("./panelTypes").RelationshipIds;
export declare const useDiscoveryPanelFavoriteOperations: () => import("./panelTypes").ActionPanelFavoriteItem[];
export declare const useDiscoveryPanelSelectedBrowseCategory: () => {
    key: string;
    title: string;
} | undefined;
export declare const useDiscoveryPanelSelectionState: () => import("./panelTypes").DiscoveryPanelSelectionState | undefined;
export declare const useDiscoveryPanelIsOperationFavorited: (connectorId: string, operationId?: string) => boolean;
export declare const useErrorsPanelSelectedTabId: () => string | undefined;
export declare const useFocusReturnElementId: () => string | undefined;
export declare const useIsCreatingConnection: () => boolean;
export declare const useIsPanelCollapsed: () => boolean;
export declare const useIsPanelLoading: () => boolean;
export declare const useIsNodePinnedToOperationPanel: (nodeId: string) => boolean;
export declare const useIsAlternateNodePinned: () => boolean;
export declare const useIsNodeSelectedInOperationPanel: (nodeId: string) => boolean;
export declare const useIsPanelInPinnedViewMode: () => boolean;
export declare const useOperationAlternateSelectedNodeId: () => string;
export declare const useOperationAlternateSelectedNode: () => {
    nodeId?: string | undefined;
    activeTabId?: string | undefined;
    persistence?: "selected" | "pinned" | undefined;
};
export declare const useOperationPanelAlternateNodeActiveTabId: () => string | undefined;
export declare const useOperationPanelSelectedNodeId: () => string;
export declare const useOperationPanelSelectedNodeActiveTabId: () => string | undefined;
export declare const usePanelLocation: () => import("@microsoft/designer-ui").PanelLocation;
export declare const usePreviousPanelMode: () => "Error" | "Connection" | "Discovery" | "Operation" | "NodeSearch" | "WorkflowParameters" | "Assertions" | undefined;
export declare const useIsAddingAgentTool: () => boolean | undefined;
export declare const useIsRunHistoryCollapsed: () => boolean;
export declare const useMcpToolWizard: () => import("./panelTypes").McpToolWizardState | undefined;
export declare const useMcpWizardStep: () => import("./panelTypes").McpWizardStep | undefined;
export declare const useMcpWizardOperation: () => import("@microsoft/logic-apps-shared").DiscoveryOperation<import("@microsoft/logic-apps-shared").DiscoveryResultTypes> | undefined;
export declare const useMcpWizardConnectionId: () => string | undefined;
export declare const useMcpWizardAllowedTools: () => string[] | undefined;
export declare const useMcpWizardHeaders: () => Record<string, string> | undefined;
